"""分类事实归一化与编辑选项共享的离线词表。"""

from app.schemas.category import ClassificationFieldOption

TMDB_GENRE_KEYS = {
    "12": "adventure",
    "14": "fantasy",
    "16": "animation",
    "18": "drama",
    "27": "horror",
    "28": "action",
    "35": "comedy",
    "36": "history",
    "37": "western",
    "53": "thriller",
    "80": "crime",
    "99": "documentary",
    "878": "science_fiction",
    "9648": "mystery",
    "10402": "music",
    "10749": "romance",
    "10751": "family",
    "10752": "war",
    "10762": "kids",
    "10764": "reality",
    "10767": "talk",
    "10770": "tv_movie",
}

GENRE_KEY_ALIASES = {
    "action": "action",
    "动作": "action",
    "adventure": "adventure",
    "冒险": "adventure",
    "animation": "animation",
    "anime": "animation",
    "动画": "animation",
    "动漫": "animation",
    "comedy": "comedy",
    "喜剧": "comedy",
    "crime": "crime",
    "犯罪": "crime",
    "documentary": "documentary",
    "纪录": "documentary",
    "纪录片": "documentary",
    "drama": "drama",
    "剧情": "drama",
    "family": "family",
    "家庭": "family",
    "fantasy": "fantasy",
    "奇幻": "fantasy",
    "history": "history",
    "历史": "history",
    "horror": "horror",
    "恐怖": "horror",
    "kids": "kids",
    "children": "kids",
    "儿童": "kids",
    "music": "music",
    "音乐": "music",
    "mystery": "mystery",
    "悬疑": "mystery",
    "reality": "reality",
    "reality tv": "reality",
    "game show": "reality",
    "真人秀": "reality",
    "综艺": "reality",
    "romance": "romance",
    "爱情": "romance",
    "science fiction": "science_fiction",
    "sci fi": "science_fiction",
    "科幻": "science_fiction",
    "talk": "talk",
    "talk show": "talk",
    "脱口秀": "talk",
    "thriller": "thriller",
    "惊悚": "thriller",
    "tv movie": "tv_movie",
    "电视电影": "tv_movie",
    "war": "war",
    "战争": "war",
    "western": "western",
    "西部": "western",
    "classical": "classical",
    "古典": "classical",
    "electronic": "electronic",
    "电子": "electronic",
    "folk": "folk",
    "民谣": "folk",
    "hip hop": "hip_hop",
    "hip hop rap": "hip_hop",
    "说唱": "hip_hop",
    "jazz": "jazz",
    "爵士": "jazz",
    "pop": "pop",
    "流行": "pop",
    "rock": "rock",
    "摇滚": "rock",
    "soundtrack": "soundtrack",
    "原声": "soundtrack",
}

COUNTRY_CODE_ALIASES = {
    "中国": "CN",
    "中国大陆": "CN",
    "内地": "CN",
    "china": "CN",
    "香港": "HK",
    "中国香港": "HK",
    "hong kong": "HK",
    "台湾": "TW",
    "中国台湾": "TW",
    "taiwan": "TW",
    "澳门": "MO",
    "中国澳门": "MO",
    "macao": "MO",
    "日本": "JP",
    "japan": "JP",
    "韩国": "KR",
    "南韩": "KR",
    "south korea": "KR",
    "republic of korea": "KR",
    "朝鲜": "KP",
    "north korea": "KP",
    "美国": "US",
    "united states": "US",
    "united states of america": "US",
    "英国": "GB",
    "united kingdom": "GB",
    "great britain": "GB",
    "法国": "FR",
    "france": "FR",
    "德国": "DE",
    "germany": "DE",
    "意大利": "IT",
    "italy": "IT",
    "西班牙": "ES",
    "spain": "ES",
    "俄罗斯": "RU",
    "russia": "RU",
    "加拿大": "CA",
    "canada": "CA",
    "澳大利亚": "AU",
    "australia": "AU",
    "新西兰": "NZ",
    "new zealand": "NZ",
    "印度": "IN",
    "india": "IN",
    "泰国": "TH",
    "thailand": "TH",
    "新加坡": "SG",
    "singapore": "SG",
    "马来西亚": "MY",
    "malaysia": "MY",
    "越南": "VN",
    "vietnam": "VN",
    "印度尼西亚": "ID",
    "indonesia": "ID",
    "菲律宾": "PH",
    "philippines": "PH",
    "巴西": "BR",
    "brazil": "BR",
    "墨西哥": "MX",
    "mexico": "MX",
}


# 中文标签随 ISO 代码离线发布（CLDR / Intl.DisplayNames），不依赖运行时联网。
COUNTRY_NAMES = {
    "AD": "安道尔",
    "AE": "阿拉伯联合酋长国",
    "AF": "阿富汗",
    "AG": "安提瓜和巴布达",
    "AI": "安圭拉",
    "AL": "阿尔巴尼亚",
    "AM": "亚美尼亚",
    "AO": "安哥拉",
    "AQ": "南极洲",
    "AR": "阿根廷",
    "AS": "美属萨摩亚",
    "AT": "奥地利",
    "AU": "澳大利亚",
    "AW": "阿鲁巴",
    "AX": "奥兰群岛",
    "AZ": "阿塞拜疆",
    "BA": "波斯尼亚和黑塞哥维那",
    "BB": "巴巴多斯",
    "BD": "孟加拉国",
    "BE": "比利时",
    "BF": "布基纳法索",
    "BG": "保加利亚",
    "BH": "巴林",
    "BI": "布隆迪",
    "BJ": "贝宁",
    "BL": "圣巴泰勒米",
    "BM": "百慕大",
    "BN": "文莱",
    "BO": "玻利维亚",
    "BQ": "荷属加勒比区",
    "BR": "巴西",
    "BS": "巴哈马",
    "BT": "不丹",
    "BV": "布韦岛",
    "BW": "博茨瓦纳",
    "BY": "白俄罗斯",
    "BZ": "伯利兹",
    "CA": "加拿大",
    "CC": "科科斯（基林）群岛",
    "CD": "刚果（金）",
    "CF": "中非共和国",
    "CG": "刚果（布）",
    "CH": "瑞士",
    "CI": "科特迪瓦",
    "CK": "库克群岛",
    "CL": "智利",
    "CM": "喀麦隆",
    "CN": "中国",
    "CO": "哥伦比亚",
    "CR": "哥斯达黎加",
    "CU": "古巴",
    "CV": "佛得角",
    "CW": "库拉索",
    "CX": "圣诞岛",
    "CY": "塞浦路斯",
    "CZ": "捷克",
    "DE": "德国",
    "DJ": "吉布提",
    "DK": "丹麦",
    "DM": "多米尼克",
    "DO": "多米尼加共和国",
    "DZ": "阿尔及利亚",
    "EC": "厄瓜多尔",
    "EE": "爱沙尼亚",
    "EG": "埃及",
    "EH": "西撒哈拉",
    "ER": "厄立特里亚",
    "ES": "西班牙",
    "ET": "埃塞俄比亚",
    "FI": "芬兰",
    "FJ": "斐济",
    "FK": "福克兰群岛",
    "FM": "密克罗尼西亚",
    "FO": "法罗群岛",
    "FR": "法国",
    "GA": "加蓬",
    "GB": "英国",
    "GD": "格林纳达",
    "GE": "格鲁吉亚",
    "GF": "法属圭亚那",
    "GG": "根西岛",
    "GH": "加纳",
    "GI": "直布罗陀",
    "GL": "格陵兰",
    "GM": "冈比亚",
    "GN": "几内亚",
    "GP": "瓜德罗普",
    "GQ": "赤道几内亚",
    "GR": "希腊",
    "GS": "南乔治亚和南桑威奇群岛",
    "GT": "危地马拉",
    "GU": "关岛",
    "GW": "几内亚比绍",
    "GY": "圭亚那",
    "HK": "中国香港特别行政区",
    "HM": "赫德岛和麦克唐纳群岛",
    "HN": "洪都拉斯",
    "HR": "克罗地亚",
    "HT": "海地",
    "HU": "匈牙利",
    "ID": "印度尼西亚",
    "IE": "爱尔兰",
    "IL": "以色列",
    "IM": "马恩岛",
    "IN": "印度",
    "IO": "英属印度洋领地",
    "IQ": "伊拉克",
    "IR": "伊朗",
    "IS": "冰岛",
    "IT": "意大利",
    "JE": "泽西岛",
    "JM": "牙买加",
    "JO": "约旦",
    "JP": "日本",
    "KE": "肯尼亚",
    "KG": "吉尔吉斯斯坦",
    "KH": "柬埔寨",
    "KI": "基里巴斯",
    "KM": "科摩罗",
    "KN": "圣基茨和尼维斯",
    "KP": "朝鲜",
    "KR": "韩国",
    "KW": "科威特",
    "KY": "开曼群岛",
    "KZ": "哈萨克斯坦",
    "LA": "老挝",
    "LB": "黎巴嫩",
    "LC": "圣卢西亚",
    "LI": "列支敦士登",
    "LK": "斯里兰卡",
    "LR": "利比里亚",
    "LS": "莱索托",
    "LT": "立陶宛",
    "LU": "卢森堡",
    "LV": "拉脱维亚",
    "LY": "利比亚",
    "MA": "摩洛哥",
    "MC": "摩纳哥",
    "MD": "摩尔多瓦",
    "ME": "黑山",
    "MF": "法属圣马丁",
    "MG": "马达加斯加",
    "MH": "马绍尔群岛",
    "MK": "北马其顿",
    "ML": "马里",
    "MM": "缅甸",
    "MN": "蒙古",
    "MO": "中国澳门特别行政区",
    "MP": "北马里亚纳群岛",
    "MQ": "马提尼克",
    "MR": "毛里塔尼亚",
    "MS": "蒙特塞拉特",
    "MT": "马耳他",
    "MU": "毛里求斯",
    "MV": "马尔代夫",
    "MW": "马拉维",
    "MX": "墨西哥",
    "MY": "马来西亚",
    "MZ": "莫桑比克",
    "NA": "纳米比亚",
    "NC": "新喀里多尼亚",
    "NE": "尼日尔",
    "NF": "诺福克岛",
    "NG": "尼日利亚",
    "NI": "尼加拉瓜",
    "NL": "荷兰",
    "NO": "挪威",
    "NP": "尼泊尔",
    "NR": "瑙鲁",
    "NU": "纽埃",
    "NZ": "新西兰",
    "OM": "阿曼",
    "PA": "巴拿马",
    "PE": "秘鲁",
    "PF": "法属波利尼西亚",
    "PG": "巴布亚新几内亚",
    "PH": "菲律宾",
    "PK": "巴基斯坦",
    "PL": "波兰",
    "PM": "圣皮埃尔和密克隆群岛",
    "PN": "皮特凯恩群岛",
    "PR": "波多黎各",
    "PS": "巴勒斯坦领土",
    "PT": "葡萄牙",
    "PW": "帕劳",
    "PY": "巴拉圭",
    "QA": "卡塔尔",
    "RE": "留尼汪",
    "RO": "罗马尼亚",
    "RS": "塞尔维亚",
    "RU": "俄罗斯",
    "RW": "卢旺达",
    "SA": "沙特阿拉伯",
    "SB": "所罗门群岛",
    "SC": "塞舌尔",
    "SD": "苏丹",
    "SE": "瑞典",
    "SG": "新加坡",
    "SH": "圣赫勒拿",
    "SI": "斯洛文尼亚",
    "SJ": "斯瓦尔巴和扬马延",
    "SK": "斯洛伐克",
    "SL": "塞拉利昂",
    "SM": "圣马力诺",
    "SN": "塞内加尔",
    "SO": "索马里",
    "SR": "苏里南",
    "SS": "南苏丹",
    "ST": "圣多美和普林西比",
    "SV": "萨尔瓦多",
    "SX": "荷属圣马丁",
    "SY": "叙利亚",
    "SZ": "斯威士兰",
    "TC": "特克斯和凯科斯群岛",
    "TD": "乍得",
    "TF": "法属南部领地",
    "TG": "多哥",
    "TH": "泰国",
    "TJ": "塔吉克斯坦",
    "TK": "托克劳",
    "TL": "东帝汶",
    "TM": "土库曼斯坦",
    "TN": "突尼斯",
    "TO": "汤加",
    "TR": "土耳其",
    "TT": "特立尼达和多巴哥",
    "TV": "图瓦卢",
    "TW": "台湾",
    "TZ": "坦桑尼亚",
    "UA": "乌克兰",
    "UG": "乌干达",
    "UM": "美国本土外小岛屿",
    "US": "美国",
    "UY": "乌拉圭",
    "UZ": "乌兹别克斯坦",
    "VA": "梵蒂冈",
    "VC": "圣文森特和格林纳丁斯",
    "VE": "委内瑞拉",
    "VG": "英属维尔京群岛",
    "VI": "美属维尔京群岛",
    "VN": "越南",
    "VU": "瓦努阿图",
    "WF": "瓦利斯和富图纳",
    "WS": "萨摩亚",
    "YE": "也门",
    "YT": "马约特",
    "ZA": "南非",
    "ZM": "赞比亚",
    "ZW": "津巴布韦",
}

LANGUAGE_NAMES = {
    "aa": "阿法尔语",
    "ab": "阿布哈西亚语",
    "ae": "阿维斯塔语",
    "af": "南非荷兰语",
    "ak": "阿肯语",
    "am": "阿姆哈拉语",
    "an": "阿拉贡语",
    "ar": "阿拉伯语",
    "as": "阿萨姆语",
    "av": "阿瓦尔语",
    "ay": "艾马拉语",
    "az": "阿塞拜疆语",
    "ba": "巴什基尔语",
    "be": "白俄罗斯语",
    "bg": "保加利亚语",
    "bh": "博杰普尔语",
    "bi": "比斯拉马语",
    "bm": "班巴拉语",
    "bn": "孟加拉语",
    "bo": "藏语",
    "br": "布列塔尼语",
    "bs": "波斯尼亚语",
    "ca": "加泰罗尼亚语",
    "ce": "车臣语",
    "ch": "查莫罗语",
    "co": "科西嘉语",
    "cr": "克里语",
    "cs": "捷克语",
    "cu": "教会斯拉夫语",
    "cv": "楚瓦什语",
    "cy": "威尔士语",
    "da": "丹麦语",
    "de": "德语",
    "dv": "迪维希语",
    "dz": "宗卡语",
    "ee": "埃维语",
    "el": "希腊语",
    "en": "英语",
    "eo": "世界语",
    "es": "西班牙语",
    "et": "爱沙尼亚语",
    "eu": "巴斯克语",
    "fa": "波斯语",
    "ff": "富拉语",
    "fi": "芬兰语",
    "fj": "斐济语",
    "fo": "法罗语",
    "fr": "法语",
    "fy": "西弗里西亚语",
    "ga": "爱尔兰语",
    "gd": "苏格兰盖尔语",
    "gl": "加利西亚语",
    "gn": "瓜拉尼语",
    "gu": "古吉拉特语",
    "gv": "马恩语",
    "ha": "豪萨语",
    "he": "希伯来语",
    "hi": "印地语",
    "ho": "希里莫图语",
    "hr": "克罗地亚语",
    "ht": "海地克里奥尔语",
    "hu": "匈牙利语",
    "hy": "亚美尼亚语",
    "hz": "赫雷罗语",
    "ia": "国际语",
    "id": "印度尼西亚语",
    "ie": "国际文字（E）",
    "ig": "伊博语",
    "ii": "凉山彝语",
    "ik": "伊努皮克语",
    "io": "伊多语",
    "is": "冰岛语",
    "it": "意大利语",
    "iu": "因纽特语",
    "ja": "日语",
    "jv": "爪哇语",
    "ka": "格鲁吉亚语",
    "kg": "刚果语",
    "ki": "吉库尤语",
    "kj": "宽亚玛语",
    "kk": "哈萨克语",
    "kl": "格陵兰语",
    "km": "高棉语",
    "kn": "卡纳达语",
    "ko": "韩语",
    "kr": "卡努里语",
    "ks": "克什米尔语",
    "ku": "库尔德语",
    "kv": "科米语",
    "kw": "康沃尔语",
    "ky": "吉尔吉斯语",
    "la": "拉丁语",
    "lb": "卢森堡语",
    "lg": "卢干达语",
    "li": "林堡语",
    "ln": "林加拉语",
    "lo": "老挝语",
    "lt": "立陶宛语",
    "lu": "鲁巴加丹加语",
    "lv": "拉脱维亚语",
    "mg": "马拉加斯语",
    "mh": "马绍尔语",
    "mi": "毛利语",
    "mk": "马其顿语",
    "ml": "马拉雅拉姆语",
    "mn": "蒙古语",
    "mr": "马拉地语",
    "ms": "马来语",
    "mt": "马耳他语",
    "my": "缅甸语",
    "na": "瑙鲁语",
    "nb": "书面挪威语",
    "nd": "北恩德贝勒语",
    "ne": "尼泊尔语",
    "ng": "恩东加语",
    "nl": "荷兰语",
    "nn": "挪威尼诺斯克语",
    "no": "挪威语",
    "nr": "南恩德贝勒语",
    "nv": "纳瓦霍语",
    "ny": "齐切瓦语",
    "oc": "奥克语",
    "oj": "奥吉布瓦语",
    "om": "奥罗莫语",
    "or": "奥里亚语",
    "os": "奥塞梯语",
    "pa": "旁遮普语",
    "pi": "巴利语",
    "pl": "波兰语",
    "ps": "普什图语",
    "pt": "葡萄牙语",
    "qu": "克丘亚语",
    "rm": "罗曼什语",
    "rn": "隆迪语",
    "ro": "罗马尼亚语",
    "ru": "俄语",
    "rw": "卢旺达语",
    "sa": "梵语",
    "sc": "萨丁语",
    "sd": "信德语",
    "se": "北方萨米语",
    "sg": "桑戈语",
    "si": "僧伽罗语",
    "sk": "斯洛伐克语",
    "sl": "斯洛文尼亚语",
    "sm": "萨摩亚语",
    "sn": "绍纳语",
    "so": "索马里语",
    "sq": "阿尔巴尼亚语",
    "sr": "塞尔维亚语",
    "ss": "斯瓦蒂语",
    "st": "南索托语",
    "su": "巽他语",
    "sv": "瑞典语",
    "sw": "斯瓦希里语",
    "ta": "泰米尔语",
    "te": "泰卢固语",
    "tg": "塔吉克语",
    "th": "泰语",
    "ti": "提格利尼亚语",
    "tk": "土库曼语",
    "tl": "菲律宾语",
    "tn": "茨瓦纳语",
    "to": "汤加语",
    "tr": "土耳其语",
    "ts": "聪加语",
    "tt": "鞑靼语",
    "tw": "阿肯语",
    "ty": "塔希提语",
    "ug": "维吾尔语",
    "uk": "乌克兰语",
    "ur": "乌尔都语",
    "uz": "乌兹别克语",
    "ve": "文达语",
    "vi": "越南语",
    "vo": "沃拉普克语",
    "wa": "瓦隆语",
    "wo": "沃洛夫语",
    "xh": "科萨语",
    "yi": "意第绪语",
    "yo": "约鲁巴语",
    "za": "壮语",
    "zh": "中文",
    "zu": "祖鲁语",
}


def classification_field_options(field_id: str) -> list[ClassificationFieldOption]:
    """返回可直接保存的规范值；开放字段的字典是建议，不限制未知来源值。"""
    genre_names = {value: key for key, value in GENRE_KEY_ALIASES.items() if not key.isascii()}
    catalogs = {
        "media.countries": COUNTRY_NAMES,
        "music.artist_country": COUNTRY_NAMES,
        "media.language": LANGUAGE_NAMES,
        "media.genre_keys": genre_names,
        "music.entity_type": {"recording": "歌曲", "album": "专辑", "artist": "艺术家"},
    }
    return [ClassificationFieldOption(value=value, label=label) for value, label in catalogs.get(field_id, {}).items()]


def classification_source_options(field_id: str) -> dict[str, list[ClassificationFieldOption]]:
    """来源原始风格沿用发现页候选，开放标签不伪装成完整枚举。"""
    music_catalogs = {
        "music.album_type": {"Album": "专辑", "Single": "单曲", "EP": "迷你专辑", "Broadcast": "广播", "Other": "其他"},
        "music.secondary_types": {
            value: value
            for value in (
                "Compilation",
                "Soundtrack",
                "Spokenword",
                "Interview",
                "Audiobook",
                "Audio drama",
                "Live",
                "Remix",
                "DJ-mix",
                "Mixtape/Street",
            )
        },
        "music.release_status": {
            "Official": "正式发行",
            "Promotion": "宣传发行",
            "Bootleg": "非官方发行",
            "Pseudo-Release": "伪发行",
        },
    }
    if field_id in music_catalogs:
        return {
            "musicbrainz": [
                ClassificationFieldOption(value=value, label=label) for value, label in music_catalogs[field_id].items()
            ],
        }
    if field_id != "media.genre_names":
        return {}
    genres = {
        "themoviedb": "动作 冒险 动画 喜剧 犯罪 纪录 剧情 家庭 奇幻 历史 恐怖 音乐 悬疑 爱情 科幻 电视电影 惊悚 战争 西部 儿童 新闻 真人秀 肥皂剧 脱口秀".split(),
        "douban": "剧情 喜剧 爱情 动作 科幻 动画 悬疑 犯罪 惊悚 冒险 音乐 历史 奇幻 恐怖 战争 传记 歌舞 武侠 情色 灾难 西部 纪录片 短片".split(),
        "anilist": [
            "Action",
            "Adventure",
            "Comedy",
            "Drama",
            "Fantasy",
            "Horror",
            "Mahou Shoujo",
            "Mecha",
            "Music",
            "Mystery",
            "Psychological",
            "Romance",
            "Sci-Fi",
            "Slice of Life",
            "Sports",
            "Supernatural",
            "Thriller",
        ],
    }
    genres["themoviedb"].extend(["动作冒险", "Sci-Fi & Fantasy", "War & Politics"])
    return {
        source: [ClassificationFieldOption(value=value, label=value) for value in values]
        for source, values in genres.items()
    }
