import importlib

import sqlalchemy as sa
from alembic.migration import MigrationContext
from alembic.operations import Operations
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable

from app.db.models.pluginconfig import PluginConfig


MIGRATION = "database.versions.f8767f021120_3_0_8"
# 建表之后修订该表结构的迁移，按修订顺序排列
FOLLOW_UP_MIGRATIONS = ("database.versions.27c3b2eb9b1e_3_0_10",)


def _bind_migration(monkeypatch, connection, module_name: str = MIGRATION):
    """把迁移绑定到隔离数据库连接。"""
    migration = importlib.import_module(module_name)
    context = MigrationContext.configure(connection)
    monkeypatch.setattr(migration, "op", Operations(context))
    return migration


def test_plugin_config_migration_upgrades_empty_schema_and_downgrades(monkeypatch) -> None:
    """空库应可重复升级建表，并完整回滚新增结构。"""
    engine = sa.create_engine("sqlite://")
    with engine.begin() as connection:
        migration = _bind_migration(monkeypatch, connection)

        migration.upgrade()
        migration.upgrade()

        inspector = sa.inspect(connection)
        assert "pluginconfig" in inspector.get_table_names()

        unique_names = {
            constraint.get("name")
            for constraint in inspector.get_unique_constraints("pluginconfig")
        }
        assert "ux_pluginconfig_plugin_instance" in unique_names

        indexes = {
            index["name"]: (tuple(index["column_names"]), index["unique"])
            for index in inspector.get_indexes("pluginconfig")
        }
        assert indexes["ix_pluginconfig_plugin_id"] == (("plugin_id",), 0)
        assert indexes["ix_pluginconfig_plugin_id_plugin_version"] == (
            ("plugin_id", "plugin_version"),
            0,
        )

        migration.downgrade()
        inspector = sa.inspect(connection)
        assert "pluginconfig" not in inspector.get_table_names()


def test_plugin_config_migration_chain_converges_to_model_columns(monkeypatch) -> None:
    """建表迁移与其后续修订串起来后，表结构必须与模型完全一致。

    建表迁移单独跑只能建出它那一版的列，后续修订新增的列由各自的迁移补齐；只有整条
    链收敛到模型，全新安装（create_all）与老库升级（alembic）才会落到同一个结构上。
    """
    engine = sa.create_engine("sqlite://")
    with engine.begin() as connection:
        migrations = [_bind_migration(monkeypatch, connection)]
        migrations.extend(
            _bind_migration(monkeypatch, connection, name) for name in FOLLOW_UP_MIGRATIONS
        )
        for migration in migrations:
            migration.upgrade()
            migration.upgrade()

        inspector = sa.inspect(connection)
        columns = {column["name"] for column in inspector.get_columns("pluginconfig")}
        assert columns == {column.name for column in PluginConfig.__table__.columns}

        for migration in reversed(migrations):
            migration.downgrade()
        assert "pluginconfig" not in sa.inspect(connection).get_table_names()


def test_plugin_config_migration_accepts_fresh_current_schema(monkeypatch) -> None:
    """create_all 已建立当前结构时，迁移重复升级不得创建冲突对象。"""
    engine = sa.create_engine("sqlite://")
    with engine.begin() as connection:
        PluginConfig.__table__.create(connection)
        migration = _bind_migration(monkeypatch, connection)

        migration.upgrade()
        migration.upgrade()

        inspector = sa.inspect(connection)
        assert "pluginconfig" in inspector.get_table_names()
        assert {
            column["name"] for column in inspector.get_columns("pluginconfig")
        } == {column.name for column in PluginConfig.__table__.columns}


def test_plugin_config_migration_matches_postgresql_identity() -> None:
    """独立 Alembic 路径应与 PostgreSQL create_all 使用相同 Identity。"""
    migration = importlib.import_module(MIGRATION)
    metadata = sa.MetaData()
    table = sa.Table(
        "pluginconfig",
        metadata,
        migration._id_column("postgresql"),
    )

    identity = table.c.id.identity
    assert identity is not None
    assert identity.start == 1
    assert identity.cycle is True
    ddl = str(CreateTable(table).compile(dialect=postgresql.dialect()))
    assert "GENERATED BY DEFAULT AS IDENTITY" in ddl
    assert "CYCLE" in ddl
