"""Agent 结构化 MoviePilot API 操作与固定路由注册表。"""

from dataclasses import dataclass
from typing import Optional

from app.agent.policy.contracts import (
    ActionEffect,
    ConfirmationMode,
    PrincipalRole,
    RecoveryMode,
    ResultSensitivity,
)


@dataclass(frozen=True)
class ApiOperationSpec:
    """描述一个可由 Agent API 网关调用的稳定业务操作。"""

    operation_id: str
    effect: ActionEffect
    required_role: PrincipalRole
    confirmation: ConfirmationMode
    recovery: RecoveryMode
    result_sensitivity: ResultSensitivity


@dataclass(frozen=True)
class ApiOperationRoute:
    """描述一个固定 API 路由，禁止调用方注入任意 URL 或 HTTP 方法。"""

    method: str
    path: str


_ADMIN = PrincipalRole.SYSTEM_ADMIN
_CONFIRM = ConfirmationMode.REQUIRED
_IDEMPOTENT = RecoveryMode.IDEMPOTENT
_DELETE_RECOVERABLE = RecoveryMode.RECOVERABLE_DELETE


def _spec(
    operation_id: str,
    *,
    effect: ActionEffect = ActionEffect.SAFE_READ,
    required_role: PrincipalRole = PrincipalRole.USER,
    confirmation: ConfirmationMode = ConfirmationMode.NONE,
    recovery: RecoveryMode = RecoveryMode.NONE,
    result_sensitivity: ResultSensitivity = ResultSensitivity.NORMAL,
) -> ApiOperationSpec:
    """构造不可变 API 操作描述。"""
    return ApiOperationSpec(
        operation_id=operation_id,
        effect=effect,
        required_role=required_role,
        confirmation=confirmation,
        recovery=recovery,
        result_sensitivity=result_sensitivity,
    )


def _write(
    operation_id: str,
    *,
    effect: ActionEffect = ActionEffect.REVERSIBLE_WRITE,
    recovery: RecoveryMode = _IDEMPOTENT,
    sensitivity: ResultSensitivity = ResultSensitivity.NORMAL,
) -> ApiOperationSpec:
    """构造管理员确认写操作。"""
    return _spec(
        operation_id,
        effect=effect,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=recovery,
        result_sensitivity=sensitivity,
    )


def _admin_read(
    operation_id: str,
    *,
    sensitivity: ResultSensitivity = ResultSensitivity.NORMAL,
) -> ApiOperationSpec:
    """构造管理员读取操作。"""
    return _spec(operation_id, required_role=_ADMIN, result_sensitivity=sensitivity)


def _user_write(
    operation_id: str,
    *,
    effect: ActionEffect = ActionEffect.REVERSIBLE_WRITE,
    recovery: RecoveryMode = _IDEMPOTENT,
    sensitivity: ResultSensitivity = ResultSensitivity.NORMAL,
) -> ApiOperationSpec:
    """构造保留普通用户 API 权限的确认写操作。"""
    return _spec(
        operation_id,
        effect=effect,
        confirmation=_CONFIRM,
        recovery=recovery,
        result_sensitivity=sensitivity,
    )


API_FIRST_BATCH_OPERATION_SPECS: tuple[ApiOperationSpec, ...] = (
    _spec("media.search"),
    _spec("media.person.search"),
    _spec("media.person.credits"),
    _spec("media.recognize"),
    _spec("media.scrape", effect=ActionEffect.EXTERNAL_SIDE_EFFECT, required_role=_ADMIN, confirmation=_CONFIRM),
    _spec("media.episode_schedule"),
    _spec("media.detail"),
    _write("subscription.add"),
    _write("subscription.update"),
    _spec("subscription.search"),
    _spec("subscription.list"),
    _spec("subscription.shares"),
    _spec("subscription.popular"),
    _spec("subscription.history"),
    _write("subscription.delete", effect=ActionEffect.DESTRUCTIVE_WRITE, recovery=_DELETE_RECOVERABLE),
    _spec("download.add", effect=ActionEffect.EXTERNAL_SIDE_EFFECT, confirmation=_CONFIRM, recovery=_IDEMPOTENT),
    _spec("download.tasks.active"),
    _spec("download.clients"),
    _spec("download.paths"),
    _spec("download.history.list"),
    _write("download.history.delete", effect=ActionEffect.DESTRUCTIVE_WRITE, recovery=_DELETE_RECOVERABLE),
    _write("transfer.history.delete", effect=ActionEffect.DESTRUCTIVE_WRITE, recovery=_DELETE_RECOVERABLE),
    _write("site.update"),
    _spec("site.list"),
    _admin_read("site.userdata", sensitivity=ResultSensitivity.PRIVATE),
    _spec("site.test"),
    _write("site.cookie.update", sensitivity=ResultSensitivity.PRIVATE),
    _spec("recommendation.list"),
    _spec("library.exists"),
    _spec("library.latest"),
    _admin_read("storage.settings"),
    _spec("storage.list", result_sensitivity=ResultSensitivity.PRIVATE),
    _spec("transfer.history", result_sensitivity=ResultSensitivity.PRIVATE),
    _spec(
        "transfer.file",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _admin_read("scheduler.list"),
    _spec(
        "scheduler.run",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _spec("workflow.list"),
    _spec(
        "workflow.run",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _admin_read("plugin.installed"),
    _admin_read("plugin.market"),
    _admin_read("plugin.capabilities"),
    _admin_read("plugin.config.get", sensitivity=ResultSensitivity.PRIVATE),
    _write("plugin.config.update", sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("plugin.source.options"),
    _spec(
        "plugin.source.install",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _spec(
        "plugin.source.change",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _spec(
        "plugin.reload",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _spec(
        "plugin.install",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _write("plugin.uninstall", effect=ActionEffect.DESTRUCTIVE_WRITE, recovery=_DELETE_RECOVERABLE),
    _admin_read("slash.list"),
    _admin_read("config.identifiers.get"),
    _write("config.identifiers.update"),
)


API_PARITY_OPERATION_SPECS: tuple[ApiOperationSpec, ...] = (
    _spec("search.torrents"),
    _spec("search.results"),
    _spec("filter.builtin"),
    _spec("filter.custom"),
    _spec("filter.groups"),
    _write("filter.custom.add", recovery=RecoveryMode.TRANSACTION),
    _write("filter.custom.update", recovery=RecoveryMode.TRANSACTION),
    _write("filter.custom.delete", effect=ActionEffect.DESTRUCTIVE_WRITE, recovery=RecoveryMode.TRANSACTION),
    _write("filter.group.add", recovery=RecoveryMode.TRANSACTION),
    _write("filter.group.update", recovery=RecoveryMode.TRANSACTION),
    _write("filter.group.delete", effect=ActionEffect.DESTRUCTIVE_WRITE, recovery=RecoveryMode.TRANSACTION),
    _admin_read("plugin.data", sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("config.system.get", sensitivity=ResultSensitivity.PRIVATE),
    _write("config.system.update", recovery=RecoveryMode.TRANSACTION, sensitivity=ResultSensitivity.PRIVATE),
    _spec(
        "slash.run",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
)

API_MUSIC_OPERATION_SPECS: tuple[ApiOperationSpec, ...] = (
    _spec("music.recognize"),
    _spec("music.explore"),
    _spec("music.album.get"),
    _spec("music.album.related"),
    _spec("music.artist.get"),
    _spec("music.artist.albums"),
    _spec("music.artist.related"),
    _admin_read("music.cache.get", sensitivity=ResultSensitivity.PRIVATE),
    _write(
        "music.cache.delete",
        effect=ActionEffect.DESTRUCTIVE_WRITE,
        recovery=RecoveryMode.NONE,
    ),
    _write(
        "music.cache.clear",
        effect=ActionEffect.DESTRUCTIVE_WRITE,
        recovery=RecoveryMode.NONE,
    ),
)

API_SYSTEM_OPERATION_SPECS: tuple[ApiOperationSpec, ...] = (
    _admin_read("system.versions"),
    _admin_read("system.update.status"),
    _spec(
        "system.update.check",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        recovery=_IDEMPOTENT,
    ),
    _spec(
        "system.update.download",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _spec(
        "system.restart",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _spec(
        "system.update.install",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _spec(
        "system.upgrade.dev",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
)


API_EXTENDED_OPERATION_SPECS: tuple[ApiOperationSpec, ...] = (
    _admin_read("dashboard.media.statistics", sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("dashboard.storage", sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("dashboard.processes", sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("dashboard.system", sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("dashboard.downloader", sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("scheduler.progress"),
    _admin_read("dashboard.transfer.statistics"),
    _admin_read("dashboard.cpu"),
    _admin_read("dashboard.memory"),
    _admin_read("dashboard.network"),
    _spec("media.sources"),
    _spec("media.recognize_file"),
    _spec("media.category.config.get"),
    _spec("media.categories"),
    _spec("media.episode_groups"),
    _spec("media.episode_group.seasons"),
    _spec("media.seasons"),
    _spec("search.title", effect=ActionEffect.EXTERNAL_SIDE_EFFECT, recovery=_IDEMPOTENT),
    _spec("search.recommend", effect=ActionEffect.EXTERNAL_SIDE_EFFECT, recovery=_IDEMPOTENT),
    _spec("subtitle.search.title", effect=ActionEffect.EXTERNAL_SIDE_EFFECT, recovery=_IDEMPOTENT),
    _spec("subtitle.search.media", effect=ActionEffect.EXTERNAL_SIDE_EFFECT, recovery=_IDEMPOTENT),
    _write("site.add", recovery=RecoveryMode.TRANSACTION, sensitivity=ResultSensitivity.PRIVATE),
    _write(
        "site.delete",
        effect=ActionEffect.DESTRUCTIVE_WRITE,
        recovery=_DELETE_RECOVERABLE,
    ),
    _spec("site.auth.options"),
    _spec(
        "site.authenticate",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
        result_sensitivity=ResultSensitivity.PRIVATE,
    ),
    _spec(
        "site.cookiecloud.sync",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _write(
        "site.reset",
        effect=ActionEffect.DESTRUCTIVE_WRITE,
        recovery=RecoveryMode.RECONCILE,
    ),
    _write("site.priorities.update", recovery=RecoveryMode.TRANSACTION),
    _spec(
        "site.userdata.refresh",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=_IDEMPOTENT,
        result_sensitivity=ResultSensitivity.PRIVATE,
    ),
    _admin_read("site.userdata.latest", sensitivity=ResultSensitivity.PRIVATE),
    _spec("site.category"),
    _spec(
        "site.resource",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        recovery=_IDEMPOTENT,
        result_sensitivity=ResultSensitivity.PRIVATE,
    ),
    _admin_read("site.searchable", sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("site.rss", sensitivity=ResultSensitivity.PRIVATE),
    _spec("site.statistics", result_sensitivity=ResultSensitivity.PRIVATE),
    _spec("site.statistic", result_sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("site.mapping", sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("site.supporting"),
    _spec("subscription.get"),
    _spec("subscription.find"),
    _user_write(
        "subscription.delete_by_media",
        effect=ActionEffect.DESTRUCTIVE_WRITE,
        recovery=_DELETE_RECOVERABLE,
    ),
    _user_write("subscription.status.update"),
    _user_write("subscription.reset"),
    _spec("subscription.search_all", effect=ActionEffect.EXTERNAL_SIDE_EFFECT, recovery=_IDEMPOTENT),
    _spec(
        "subscription.refresh",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _spec(
        "subscription.metadata.refresh",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _user_write(
        "subscription.history.delete",
        effect=ActionEffect.DESTRUCTIVE_WRITE,
        recovery=_DELETE_RECOVERABLE,
    ),
    _spec("subscription.user.list"),
    _spec("subscription.files", result_sensitivity=ResultSensitivity.PRIVATE),
    _user_write("subscription.share", effect=ActionEffect.EXTERNAL_SIDE_EFFECT, recovery=RecoveryMode.RECONCILE),
    _user_write(
        "subscription.share.delete",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        recovery=RecoveryMode.RECONCILE,
    ),
    _user_write("subscription.fork", effect=ActionEffect.EXTERNAL_SIDE_EFFECT, recovery=RecoveryMode.RECONCILE),
    _spec("subscription.follow.list"),
    _user_write("subscription.follow.add"),
    _user_write("subscription.follow.delete"),
    _spec("subscription.share.statistics"),
    _spec(
        "storage.manage",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
        result_sensitivity=ResultSensitivity.PRIVATE,
    ),
    _write("storage.mkdir", recovery=RecoveryMode.TRANSACTION),
    _write("storage.rename", recovery=RecoveryMode.RECONCILE),
    _write(
        "storage.delete",
        effect=ActionEffect.DESTRUCTIVE_WRITE,
        recovery=RecoveryMode.MANUAL_ONLY,
    ),
    _spec("transfer.queue", result_sensitivity=ResultSensitivity.PRIVATE),
    _user_write(
        "transfer.queue.delete",
        effect=ActionEffect.DESTRUCTIVE_WRITE,
        recovery=RecoveryMode.RECONCILE,
    ),
    _admin_read("transfer.name"),
    _admin_read("transfer.target_path", sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("transfer.manual_history", sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("transfer.episode_format.recommend", sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("transfer.manual_reviews", sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("transfer.manual_review", sensitivity=ResultSensitivity.PRIVATE),
    _write("transfer.manual_review.resolve", recovery=RecoveryMode.RECONCILE),
    _spec(
        "transfer.history.redo",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _spec(
        "transfer.history.redo_batch",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _write(
        "transfer.history.clear",
        effect=ActionEffect.DESTRUCTIVE_WRITE,
        recovery=RecoveryMode.MANUAL_ONLY,
    ),
    _write("workflow.create", recovery=RecoveryMode.TRANSACTION),
    _admin_read("workflow.get", sensitivity=ResultSensitivity.PRIVATE),
    _write("workflow.update", recovery=RecoveryMode.TRANSACTION),
    _write("workflow.delete", effect=ActionEffect.DESTRUCTIVE_WRITE, recovery=_DELETE_RECOVERABLE),
    _admin_read("workflow.actions"),
    _admin_read("workflow.event_types"),
    _admin_read("workflow.plugin.actions"),
    _write("workflow.start"),
    _write("workflow.pause"),
    _write("workflow.reset", recovery=RecoveryMode.TRANSACTION),
    _spec("workflow.shares", required_role=_ADMIN),
    _spec(
        "workflow.share",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _spec(
        "workflow.share.delete",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _spec(
        "workflow.fork",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _admin_read("torrent.cache.get", sensitivity=ResultSensitivity.PRIVATE),
    _write("torrent.cache.delete", effect=ActionEffect.DESTRUCTIVE_WRITE, recovery=RecoveryMode.NONE),
    _write("torrent.cache.clear", effect=ActionEffect.DESTRUCTIVE_WRITE, recovery=RecoveryMode.NONE),
    _spec(
        "torrent.cache.refresh",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _write("torrent.cache.reidentify", recovery=RecoveryMode.RECONCILE),
    _admin_read("database.backups.list", sensitivity=ResultSensitivity.PRIVATE),
    _spec(
        "database.backups.create",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
        result_sensitivity=ResultSensitivity.PRIVATE,
    ),
    _admin_read("database.backups.verify", sensitivity=ResultSensitivity.PRIVATE),
    _write(
        "database.backups.delete",
        effect=ActionEffect.DESTRUCTIVE_WRITE,
        recovery=RecoveryMode.MANUAL_ONLY,
    ),
    _spec("filter.test", effect=ActionEffect.EXTERNAL_SIDE_EFFECT, recovery=_IDEMPOTENT),
    _spec("system.network.targets"),
    _spec("system.network.test", effect=ActionEffect.EXTERNAL_SIDE_EFFECT, recovery=_IDEMPOTENT),
    _spec("system.module.list"),
    _spec("system.module.test", effect=ActionEffect.EXTERNAL_SIDE_EFFECT, recovery=_IDEMPOTENT),
    _spec(
        "plugin.market.sync_wiki",
        effect=ActionEffect.EXTERNAL_SIDE_EFFECT,
        required_role=_ADMIN,
        confirmation=_CONFIRM,
        recovery=RecoveryMode.RECONCILE,
    ),
    _admin_read("plugin.runtime.status", sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("plugin.history"),
    _admin_read("plugin.releases"),
    _spec("plugin.ratings"),
    _spec("plugin.rating"),
    _user_write("plugin.rating.submit", effect=ActionEffect.EXTERNAL_SIDE_EFFECT, recovery=_IDEMPOTENT),
    _spec("plugin.statistics"),
    _write(
        "plugin.reset",
        effect=ActionEffect.DESTRUCTIVE_WRITE,
        recovery=RecoveryMode.MANUAL_ONLY,
    ),
    _write("plugin.clone", effect=ActionEffect.EXTERNAL_SIDE_EFFECT, recovery=RecoveryMode.RECONCILE),
    _spec("config.user.get", result_sensitivity=ResultSensitivity.PRIVATE),
    _spec("config.public.get"),
    _spec("system.usage.statistics", result_sensitivity=ResultSensitivity.PRIVATE),
    _admin_read("plugin.folders.get", sensitivity=ResultSensitivity.PRIVATE),
    _write("plugin.folders.update", recovery=RecoveryMode.TRANSACTION),
    _write("plugin.folder.create", recovery=RecoveryMode.TRANSACTION),
    _write("plugin.folder.delete", effect=ActionEffect.DESTRUCTIVE_WRITE, recovery=_DELETE_RECOVERABLE),
    _write("plugin.folder.plugins.update", recovery=RecoveryMode.TRANSACTION),
)


API_OPERATION_SPECS: tuple[ApiOperationSpec, ...] = (
    *API_FIRST_BATCH_OPERATION_SPECS,
    *API_PARITY_OPERATION_SPECS,
    *API_MUSIC_OPERATION_SPECS,
    *API_SYSTEM_OPERATION_SPECS,
    *API_EXTENDED_OPERATION_SPECS,
)
API_OPERATION_BY_ID = {spec.operation_id: spec for spec in API_OPERATION_SPECS}


# 所有路径均由宿主注册，调用方只能传路径参数、查询参数和 JSON body。
API_OPERATION_ROUTES: dict[str, ApiOperationRoute] = {
    "media.search": ApiOperationRoute("GET", "/api/v1/media/search"),
    "media.person.search": ApiOperationRoute("GET", "/api/v1/media/search"),
    "media.person.credits": ApiOperationRoute("GET", "/api/v1/{source}/person/credits/{person_id}"),
    "media.recognize": ApiOperationRoute("GET", "/api/v1/media/recognize"),
    "media.scrape": ApiOperationRoute("POST", "/api/v1/media/scrape/{storage}"),
    "media.episode_schedule": ApiOperationRoute("GET", "/api/v1/tmdb/{tmdbid}/{season}"),
    "media.detail": ApiOperationRoute("GET", "/api/v1/media/{media_id}"),
    "music.recognize": ApiOperationRoute("POST", "/api/v1/music/recognize"),
    "music.explore": ApiOperationRoute("GET", "/api/v1/music/explore"),
    "music.album.get": ApiOperationRoute("GET", "/api/v1/music/album/{album_id}"),
    "music.album.related": ApiOperationRoute("GET", "/api/v1/music/album/{album_id}/related"),
    "music.artist.get": ApiOperationRoute("GET", "/api/v1/music/artist/{artist_id}"),
    "music.artist.albums": ApiOperationRoute("GET", "/api/v1/music/artist/{artist_id}/albums"),
    "music.artist.related": ApiOperationRoute("GET", "/api/v1/music/artist/{artist_id}/related"),
    "music.cache.get": ApiOperationRoute("GET", "/api/v1/music/cache"),
    "music.cache.delete": ApiOperationRoute("DELETE", "/api/v1/music/cache/{cache_key}"),
    "music.cache.clear": ApiOperationRoute("DELETE", "/api/v1/music/cache"),
    "subscription.add": ApiOperationRoute("POST", "/api/v1/subscribe/"),
    "subscription.update": ApiOperationRoute("PUT", "/api/v1/subscribe/"),
    "subscription.search": ApiOperationRoute("GET", "/api/v1/subscribe/search/{subscribe_id}"),
    "subscription.list": ApiOperationRoute("GET", "/api/v1/subscribe/"),
    "subscription.shares": ApiOperationRoute("GET", "/api/v1/subscribe/shares"),
    "subscription.popular": ApiOperationRoute("GET", "/api/v1/subscribe/popular"),
    "subscription.history": ApiOperationRoute("GET", "/api/v1/subscribe/history/{mtype}"),
    "subscription.delete": ApiOperationRoute("DELETE", "/api/v1/subscribe/{subscribe_id}"),
    "download.add": ApiOperationRoute("POST", "/api/v1/download/add"),
    "download.tasks.active": ApiOperationRoute("GET", "/api/v1/download/"),
    "download.clients": ApiOperationRoute("GET", "/api/v1/download/clients"),
    "download.paths": ApiOperationRoute("GET", "/api/v1/download/paths"),
    "download.history.list": ApiOperationRoute("GET", "/api/v1/history/download"),
    "download.history.delete": ApiOperationRoute("DELETE", "/api/v1/history/download"),
    "transfer.history.delete": ApiOperationRoute("DELETE", "/api/v1/history/transfer"),
    "site.list": ApiOperationRoute("GET", "/api/v1/site/agent"),
    "site.update": ApiOperationRoute("PUT", "/api/v1/site/"),
    "site.userdata": ApiOperationRoute("GET", "/api/v1/site/userdata/{site_id}"),
    "site.test": ApiOperationRoute("GET", "/api/v1/site/test/{site_id}"),
    "site.cookie.update": ApiOperationRoute("POST", "/api/v1/site/cookie/{site_id}"),
    "recommendation.list": ApiOperationRoute("GET", "/api/v1/recommend/agent"),
    "library.exists": ApiOperationRoute("GET", "/api/v1/mediaserver/exists"),
    "library.latest": ApiOperationRoute("GET", "/api/v1/mediaserver/latest"),
    "storage.settings": ApiOperationRoute("GET", "/api/v1/storage/directories"),
    "storage.list": ApiOperationRoute("POST", "/api/v1/storage/agent/list"),
    "transfer.history": ApiOperationRoute("GET", "/api/v1/history/transfer"),
    "transfer.file": ApiOperationRoute("POST", "/api/v1/transfer/manual"),
    "scheduler.list": ApiOperationRoute("GET", "/api/v1/dashboard/schedule"),
    "scheduler.run": ApiOperationRoute("GET", "/api/v1/system/runscheduler"),
    "workflow.list": ApiOperationRoute("GET", "/api/v1/workflow/agent"),
    "workflow.run": ApiOperationRoute("POST", "/api/v1/workflow/{workflow_id}/run"),
    "plugin.installed": ApiOperationRoute("GET", "/api/v1/plugin/"),
    "plugin.market": ApiOperationRoute("GET", "/api/v1/plugin/"),
    "plugin.capabilities": ApiOperationRoute("GET", "/api/v1/plugin/runtime/capabilities"),
    "plugin.config.get": ApiOperationRoute("GET", "/api/v1/plugin/form/{plugin_id}"),
    "plugin.config.update": ApiOperationRoute("PUT", "/api/v1/plugin/{plugin_id}"),
    "plugin.source.options": ApiOperationRoute("GET", "/api/v1/plugin/source/{plugin_id}"),
    "plugin.source.install": ApiOperationRoute("POST", "/api/v1/plugin/source/{plugin_id}/install"),
    "plugin.source.change": ApiOperationRoute("POST", "/api/v1/plugin/source/{plugin_id}"),
    "plugin.reload": ApiOperationRoute("GET", "/api/v1/plugin/reload/{plugin_id}"),
    "plugin.install": ApiOperationRoute("GET", "/api/v1/plugin/install/{plugin_id}"),
    "plugin.uninstall": ApiOperationRoute("DELETE", "/api/v1/plugin/{plugin_id}"),
    "slash.list": ApiOperationRoute("GET", "/api/v1/message/agent/commands"),
    "config.identifiers.get": ApiOperationRoute("GET", "/api/v1/system/identifiers"),
    "config.identifiers.update": ApiOperationRoute("POST", "/api/v1/system/identifiers"),
    "search.torrents": ApiOperationRoute("GET", "/api/v1/search/media/{media_id}"),
    "search.results": ApiOperationRoute("GET", "/api/v1/search/last/context"),
    "filter.builtin": ApiOperationRoute("GET", "/api/v1/rule/builtin"),
    "filter.custom": ApiOperationRoute("GET", "/api/v1/rule/custom"),
    "filter.groups": ApiOperationRoute("GET", "/api/v1/rule/groups"),
    "filter.custom.add": ApiOperationRoute("POST", "/api/v1/rule/custom"),
    "filter.custom.update": ApiOperationRoute("PUT", "/api/v1/rule/custom/{rule_id}"),
    "filter.custom.delete": ApiOperationRoute("DELETE", "/api/v1/rule/custom/{rule_id}"),
    "filter.group.add": ApiOperationRoute("POST", "/api/v1/rule/groups"),
    "filter.group.update": ApiOperationRoute("PUT", "/api/v1/rule/groups/{name}"),
    "filter.group.delete": ApiOperationRoute("DELETE", "/api/v1/rule/groups/{name}"),
    "plugin.data": ApiOperationRoute("GET", "/api/v1/plugin/runtime/{plugin_id}/data"),
    "config.system.get": ApiOperationRoute("GET", "/api/v1/system/settings"),
    "config.system.update": ApiOperationRoute("POST", "/api/v1/system/settings"),
    "slash.run": ApiOperationRoute("POST", "/api/v1/message/agent/commands/run"),
    "system.versions": ApiOperationRoute("GET", "/api/v1/system/versions"),
    "system.restart": ApiOperationRoute("GET", "/api/v1/system/restart"),
    "system.update.status": ApiOperationRoute("GET", "/api/v1/system/update/status"),
    "system.update.check": ApiOperationRoute("POST", "/api/v1/system/update/check"),
    "system.update.download": ApiOperationRoute("POST", "/api/v1/system/update/download"),
    "system.update.install": ApiOperationRoute("POST", "/api/v1/system/update/install"),
    "system.upgrade.dev": ApiOperationRoute("POST", "/api/v1/system/upgrade"),
    "dashboard.media.statistics": ApiOperationRoute("GET", "/api/v1/dashboard/statistic"),
    "dashboard.storage": ApiOperationRoute("GET", "/api/v1/dashboard/storage"),
    "dashboard.processes": ApiOperationRoute("GET", "/api/v1/dashboard/processes"),
    "dashboard.system": ApiOperationRoute("GET", "/api/v1/dashboard/system"),
    "dashboard.downloader": ApiOperationRoute("GET", "/api/v1/dashboard/downloader"),
    "scheduler.progress": ApiOperationRoute("GET", "/api/v1/dashboard/schedule/{job_id}/progress"),
    "dashboard.transfer.statistics": ApiOperationRoute("GET", "/api/v1/dashboard/transfer"),
    "dashboard.cpu": ApiOperationRoute("GET", "/api/v1/dashboard/cpu"),
    "dashboard.memory": ApiOperationRoute("GET", "/api/v1/dashboard/memory"),
    "dashboard.network": ApiOperationRoute("GET", "/api/v1/dashboard/network"),
    "media.sources": ApiOperationRoute("GET", "/api/v1/media/source"),
    "media.recognize_file": ApiOperationRoute("GET", "/api/v1/media/recognize_file"),
    "media.category.config.get": ApiOperationRoute("GET", "/api/v1/media/category/config"),
    "media.categories": ApiOperationRoute("GET", "/api/v1/media/category"),
    "media.episode_groups": ApiOperationRoute("GET", "/api/v1/media/groups/{tmdbid}"),
    "media.episode_group.seasons": ApiOperationRoute("GET", "/api/v1/media/group/seasons/{episode_group}"),
    "media.seasons": ApiOperationRoute("GET", "/api/v1/media/seasons"),
    "search.title": ApiOperationRoute("GET", "/api/v1/search/title"),
    "search.recommend": ApiOperationRoute("POST", "/api/v1/search/recommend"),
    "subtitle.search.title": ApiOperationRoute("GET", "/api/v1/search/subtitle/title"),
    "subtitle.search.media": ApiOperationRoute("GET", "/api/v1/search/subtitle/media/{media_id}"),
    "site.add": ApiOperationRoute("POST", "/api/v1/site/"),
    "site.delete": ApiOperationRoute("DELETE", "/api/v1/site/{site_id}"),
    "site.auth.options": ApiOperationRoute("GET", "/api/v1/site/auth"),
    "site.authenticate": ApiOperationRoute("POST", "/api/v1/site/auth"),
    "site.cookiecloud.sync": ApiOperationRoute("GET", "/api/v1/site/cookiecloud"),
    "site.reset": ApiOperationRoute("GET", "/api/v1/site/reset"),
    "site.priorities.update": ApiOperationRoute("POST", "/api/v1/site/priorities"),
    "site.userdata.refresh": ApiOperationRoute("POST", "/api/v1/site/userdata/{site_id}"),
    "site.userdata.latest": ApiOperationRoute("GET", "/api/v1/site/userdata/latest"),
    "site.category": ApiOperationRoute("GET", "/api/v1/site/category/{site_id}"),
    "site.resource": ApiOperationRoute("GET", "/api/v1/site/resource/{site_id}"),
    "site.searchable": ApiOperationRoute("GET", "/api/v1/site/media/{media_type}"),
    "site.rss": ApiOperationRoute("GET", "/api/v1/site/rss"),
    "site.statistics": ApiOperationRoute("GET", "/api/v1/site/statistic"),
    "site.statistic": ApiOperationRoute("GET", "/api/v1/site/statistic/{site_url}"),
    "site.mapping": ApiOperationRoute("GET", "/api/v1/site/mapping"),
    "site.supporting": ApiOperationRoute("GET", "/api/v1/site/supporting"),
    "subscription.get": ApiOperationRoute("GET", "/api/v1/subscribe/{subscribe_id}"),
    "subscription.find": ApiOperationRoute("GET", "/api/v1/subscribe/media/{media_id}"),
    "subscription.delete_by_media": ApiOperationRoute("DELETE", "/api/v1/subscribe/media/{media_id}"),
    "subscription.status.update": ApiOperationRoute("PUT", "/api/v1/subscribe/status/{subid}"),
    "subscription.reset": ApiOperationRoute("GET", "/api/v1/subscribe/reset/{subid}"),
    "subscription.search_all": ApiOperationRoute("GET", "/api/v1/subscribe/search"),
    "subscription.refresh": ApiOperationRoute("GET", "/api/v1/subscribe/refresh"),
    "subscription.metadata.refresh": ApiOperationRoute("GET", "/api/v1/subscribe/check"),
    "subscription.history.delete": ApiOperationRoute("DELETE", "/api/v1/subscribe/history/{history_id}"),
    "subscription.user.list": ApiOperationRoute("GET", "/api/v1/subscribe/user/{username}"),
    "subscription.files": ApiOperationRoute("GET", "/api/v1/subscribe/files/{subscribe_id}"),
    "subscription.share": ApiOperationRoute("POST", "/api/v1/subscribe/share"),
    "subscription.share.delete": ApiOperationRoute("DELETE", "/api/v1/subscribe/share/{share_id}"),
    "subscription.fork": ApiOperationRoute("POST", "/api/v1/subscribe/fork"),
    "subscription.follow.list": ApiOperationRoute("GET", "/api/v1/subscribe/follow"),
    "subscription.follow.add": ApiOperationRoute("POST", "/api/v1/subscribe/follow"),
    "subscription.follow.delete": ApiOperationRoute("DELETE", "/api/v1/subscribe/follow"),
    "subscription.share.statistics": ApiOperationRoute("GET", "/api/v1/subscribe/share/statistics"),
    "storage.manage": ApiOperationRoute("POST", "/api/v1/storage/manage"),
    "storage.mkdir": ApiOperationRoute("POST", "/api/v1/storage/mkdir"),
    "storage.rename": ApiOperationRoute("POST", "/api/v1/storage/rename"),
    "storage.delete": ApiOperationRoute("POST", "/api/v1/storage/delete"),
    "transfer.queue": ApiOperationRoute("GET", "/api/v1/transfer/queue"),
    "transfer.queue.delete": ApiOperationRoute("DELETE", "/api/v1/transfer/queue"),
    "transfer.name": ApiOperationRoute("GET", "/api/v1/transfer/name"),
    "transfer.target_path": ApiOperationRoute("POST", "/api/v1/transfer/manual/target-path"),
    "transfer.manual_history": ApiOperationRoute("POST", "/api/v1/transfer/manual/history"),
    "transfer.episode_format.recommend": ApiOperationRoute("POST", "/api/v1/transfer/episode-format/recommend"),
    "transfer.manual_reviews": ApiOperationRoute("GET", "/api/v1/transfer/tasks/manual-reviews"),
    "transfer.manual_review": ApiOperationRoute("GET", "/api/v1/transfer/tasks/{task_id}/manual-review"),
    "transfer.manual_review.resolve": ApiOperationRoute("POST", "/api/v1/transfer/tasks/{task_id}/manual-review"),
    "transfer.history.redo": ApiOperationRoute("POST", "/api/v1/history/transfer/{history_id}/ai-redo"),
    "transfer.history.redo_batch": ApiOperationRoute("POST", "/api/v1/history/transfer/ai-redo"),
    "transfer.history.clear": ApiOperationRoute("GET", "/api/v1/history/empty/transfer"),
    "workflow.create": ApiOperationRoute("POST", "/api/v1/workflow/"),
    "workflow.get": ApiOperationRoute("GET", "/api/v1/workflow/{workflow_id}"),
    "workflow.update": ApiOperationRoute("PUT", "/api/v1/workflow/{workflow_id}"),
    "workflow.delete": ApiOperationRoute("DELETE", "/api/v1/workflow/{workflow_id}"),
    "workflow.actions": ApiOperationRoute("GET", "/api/v1/workflow/actions"),
    "workflow.event_types": ApiOperationRoute("GET", "/api/v1/workflow/event_types"),
    "workflow.plugin.actions": ApiOperationRoute("GET", "/api/v1/workflow/plugin/actions"),
    "workflow.start": ApiOperationRoute("POST", "/api/v1/workflow/{workflow_id}/start"),
    "workflow.pause": ApiOperationRoute("POST", "/api/v1/workflow/{workflow_id}/pause"),
    "workflow.reset": ApiOperationRoute("POST", "/api/v1/workflow/{workflow_id}/reset"),
    "workflow.shares": ApiOperationRoute("GET", "/api/v1/workflow/shares"),
    "workflow.share": ApiOperationRoute("POST", "/api/v1/workflow/share"),
    "workflow.share.delete": ApiOperationRoute("DELETE", "/api/v1/workflow/share/{share_id}"),
    "workflow.fork": ApiOperationRoute("POST", "/api/v1/workflow/fork"),
    "torrent.cache.get": ApiOperationRoute("GET", "/api/v1/torrent/cache"),
    "torrent.cache.delete": ApiOperationRoute("DELETE", "/api/v1/torrent/cache/{domain}/{torrent_hash}"),
    "torrent.cache.clear": ApiOperationRoute("DELETE", "/api/v1/torrent/cache"),
    "torrent.cache.refresh": ApiOperationRoute("POST", "/api/v1/torrent/cache/refresh"),
    "torrent.cache.reidentify": ApiOperationRoute("POST", "/api/v1/torrent/cache/reidentify/{domain}/{torrent_hash}"),
    "database.backups.list": ApiOperationRoute("GET", "/api/v1/system/database/backups"),
    "database.backups.create": ApiOperationRoute("POST", "/api/v1/system/database/backups"),
    "database.backups.verify": ApiOperationRoute("POST", "/api/v1/system/database/backups/{name}/verify"),
    "database.backups.delete": ApiOperationRoute("DELETE", "/api/v1/system/database/backups/{name}"),
    "filter.test": ApiOperationRoute("GET", "/api/v1/system/ruletest"),
    "system.network.targets": ApiOperationRoute("GET", "/api/v1/system/nettest/targets"),
    "system.network.test": ApiOperationRoute("GET", "/api/v1/system/nettest"),
    "system.module.list": ApiOperationRoute("GET", "/api/v1/system/modulelist"),
    "system.module.test": ApiOperationRoute("GET", "/api/v1/system/moduletest/{moduleid}"),
    "plugin.market.sync_wiki": ApiOperationRoute("POST", "/api/v1/system/setting/PLUGIN_MARKET/sync-wiki"),
    "plugin.runtime.status": ApiOperationRoute("GET", "/api/v1/plugin/runtime"),
    "plugin.history": ApiOperationRoute("GET", "/api/v1/plugin/history/{plugin_id}"),
    "plugin.releases": ApiOperationRoute("GET", "/api/v1/plugin/releases/{plugin_id}"),
    "plugin.ratings": ApiOperationRoute("GET", "/api/v1/plugin/rating"),
    "plugin.rating": ApiOperationRoute("GET", "/api/v1/plugin/rating/{plugin_id}"),
    "plugin.rating.submit": ApiOperationRoute("POST", "/api/v1/plugin/rating/{plugin_id}"),
    "plugin.statistics": ApiOperationRoute("GET", "/api/v1/plugin/statistic"),
    "plugin.reset": ApiOperationRoute("GET", "/api/v1/plugin/reset/{plugin_id}"),
    "plugin.clone": ApiOperationRoute("POST", "/api/v1/plugin/clone/{plugin_id}"),
    "config.user.get": ApiOperationRoute("GET", "/api/v1/system/global/user"),
    "config.public.get": ApiOperationRoute("GET", "/api/v1/system/setting/public/{key}"),
    "system.usage.statistics": ApiOperationRoute("GET", "/api/v1/system/usage/statistic"),
    "plugin.folders.get": ApiOperationRoute("GET", "/api/v1/plugin/folders"),
    "plugin.folders.update": ApiOperationRoute("POST", "/api/v1/plugin/folders"),
    "plugin.folder.create": ApiOperationRoute("POST", "/api/v1/plugin/folders/{folder_name}"),
    "plugin.folder.delete": ApiOperationRoute("DELETE", "/api/v1/plugin/folders/{folder_name}"),
    "plugin.folder.plugins.update": ApiOperationRoute("PUT", "/api/v1/plugin/folders/{folder_name}/plugins"),
}


def resolve_api_operation(operation_id: str) -> Optional[ApiOperationSpec]:
    """按稳定 operation ID 查找 API 操作。"""
    return API_OPERATION_BY_ID.get(operation_id)


def resolve_api_route(operation_id: str) -> Optional[ApiOperationRoute]:
    """按稳定 operation ID 查找固定 API 路由。"""
    return API_OPERATION_ROUTES.get(operation_id)


def list_api_operation_ids() -> tuple[str, ...]:
    """返回按注册顺序排列的 API 操作 ID。"""
    return tuple(spec.operation_id for spec in API_OPERATION_SPECS)


__all__ = [
    "API_FIRST_BATCH_OPERATION_SPECS",
    "API_EXTENDED_OPERATION_SPECS",
    "API_MUSIC_OPERATION_SPECS",
    "API_OPERATION_BY_ID",
    "API_OPERATION_ROUTES",
    "API_OPERATION_SPECS",
    "API_PARITY_OPERATION_SPECS",
    "API_SYSTEM_OPERATION_SPECS",
    "ApiOperationRoute",
    "ApiOperationSpec",
    "list_api_operation_ids",
    "resolve_api_operation",
    "resolve_api_route",
]
