"""由 scripts/sdk/exports.py 生成，请勿手工编辑。"""

SDK_REQUIRED_EXPORTS = {
    'app.sdk.cache': {
        'AsyncCache': [('app.sdk.cache', 'AsyncCache')],
        'AsyncCacheBackend': [('app.sdk.cache', 'AsyncCacheBackend')],
        'AsyncFileBackend': [('app.sdk.cache', 'AsyncFileBackend')],
        'AsyncFileCache': [('app.sdk.cache', 'AsyncFileCache')],
        'AsyncMemoryBackend': [('app.sdk.cache', 'AsyncMemoryBackend')],
        'AsyncRedisBackend': [('app.sdk.cache', 'AsyncRedisBackend')],
        'Cache': [('app.sdk.cache', 'Cache')],
        'CacheBackend': [('app.sdk.cache', 'CacheBackend')],
        'FileBackend': [('app.sdk.cache', 'FileBackend')],
        'FileCache': [('app.sdk.cache', 'FileCache')],
        'LRUCache': [('app.sdk.cache', 'LRUCache')],
        'MemoryBackend': [('app.sdk.cache', 'MemoryBackend')],
        'RedisBackend': [('app.sdk.cache', 'RedisBackend')],
        'TTLCache': [('app.sdk.cache', 'TTLCache')],
        'async_fresh': [('app.sdk.cache', 'async_fresh')],
        'cached': [('app.sdk.cache', 'cached')],
        'fresh': [('app.sdk.cache', 'fresh')],
        'is_fresh': [('app.sdk.cache', 'is_fresh')],
    },
    'app.sdk.config': {
        'ConfigModel': [('app.runtime.config', 'ConfigModel')],
        'GlobalVar': [('app.runtime.config', 'GlobalVar')],
        'Settings': [('app.runtime.config', 'Settings')],
        'SystemConfModel': [('app.runtime.config', 'SystemConfModel')],
    },
    'app.sdk.events': {
        'Event': [('app.runtime.events', 'Event')],
        'EventManager': [('app.runtime.events', 'EventManager')],
    },
    'app.sdk.extension': {
        'PluginChian': [('app.sdk.extension', 'PluginChian')],
        '_PluginBase': [('app.sdk.extension', '_PluginBase')],
    },
    'app.sdk.logging': {
        'LogWriter': [('app.sdk.logging', 'LogWriter')],
        'logger': [('app.sdk.logging', 'logger')],
    },
    'app.sdk.media': {
        'Context': [('app.domain.context', 'Context'), ('app.sdk.media', 'Context')],
        'CustomizationMatcher': [('app.domain.meta.customization', 'CustomizationMatcher'), ('app.sdk.media', 'CustomizationMatcher')],
        'MEDIA_SOURCE_ALIASES': [('app.sdk.media', 'MEDIA_SOURCE_ALIASES')],
        'MEDIA_SOURCE_PREFIXES': [('app.sdk.media', 'MEDIA_SOURCE_PREFIXES')],
        'MUSIC_MEDIA_SOURCES': [('app.sdk.media', 'MUSIC_MEDIA_SOURCES')],
        'MUSIC_MEDIA_SOURCE_ORDER': [('app.sdk.media', 'MUSIC_MEDIA_SOURCE_ORDER')],
        'MediaInfo': [('app.domain.context', 'MediaInfo'), ('app.sdk.media', 'MediaInfo')],
        'MetaAnime': [('app.domain.meta.metaanime', 'MetaAnime'), ('app.sdk.media', 'MetaAnime')],
        'MetaBase': [('app.domain.meta.metabase', 'MetaBase'), ('app.sdk.media', 'MetaBase')],
        'MetaFieldRevision': [('app.sdk.media', 'MetaFieldRevision')],
        'MetaInfo': [('app.domain.metainfo', 'MetaInfo'), ('app.sdk.media', 'MetaInfo')],
        'MetaInfoPath': [('app.domain.metainfo', 'MetaInfoPath'), ('app.sdk.media', 'MetaInfoPath')],
        'MetaMusic': [('app.domain.meta.metamusic', 'MetaMusic'), ('app.sdk.media', 'MetaMusic')],
        'MetaParseStatus': [('app.sdk.media', 'MetaParseStatus')],
        'MetaParseTrace': [('app.sdk.media', 'MetaParseTrace')],
        'MetaParserRun': [('app.sdk.media', 'MetaParserRun')],
        'MetaVideo': [('app.domain.meta.metavideo', 'MetaVideo'), ('app.sdk.media', 'MetaVideo')],
        'MusicAlbumInfo': [('app.domain.context', 'MusicAlbumInfo'), ('app.sdk.media', 'MusicAlbumInfo')],
        'MusicArtistInfo': [('app.domain.context', 'MusicArtistInfo'), ('app.sdk.media', 'MusicArtistInfo')],
        'MusicInfo': [('app.domain.context', 'MusicInfo'), ('app.sdk.media', 'MusicInfo')],
        'MusicLyrics': [('app.domain.context', 'MusicLyrics'), ('app.sdk.media', 'MusicLyrics')],
        'MusicNameContext': [('app.domain.meta.metamusic', 'MusicNameContext'), ('app.sdk.media', 'MusicNameContext')],
        'MusicNameParseResult': [('app.domain.meta.metamusic', 'MusicNameParseResult'), ('app.sdk.media', 'MusicNameParseResult')],
        'MusicNameParser': [('app.domain.meta.metamusic', 'MusicNameParser'), ('app.sdk.media', 'MusicNameParser')],
        'MusicNamePattern': [('app.domain.meta.metamusic', 'MusicNamePattern'), ('app.sdk.media', 'MusicNamePattern')],
        'MusicNamePatternMatch': [('app.domain.meta.metamusic', 'MusicNamePatternMatch'), ('app.sdk.media', 'MusicNamePatternMatch')],
        'MusicNameRegistry': [('app.domain.meta.metamusic', 'MusicNameRegistry'), ('app.sdk.media', 'MusicNameRegistry')],
        'MusicRelease': [('app.domain.context', 'MusicRelease'), ('app.sdk.media', 'MusicRelease')],
        'NfoReader': [('app.domain.scraper', 'NfoReader'), ('app.sdk.media', 'NfoReader')],
        'ReleaseGroupsMatcher': [('app.domain.meta.releasegroup', 'ReleaseGroupsMatcher'), ('app.sdk.media', 'ReleaseGroupsMatcher')],
        'StreamingPlatforms': [('app.domain.meta.streamingplatform', 'StreamingPlatforms'), ('app.sdk.media', 'StreamingPlatforms')],
        'SubtitleInfo': [('app.domain.context', 'SubtitleInfo'), ('app.sdk.media', 'SubtitleInfo')],
        'Tokens': [('app.domain.tokens', 'Tokens'), ('app.sdk.media', 'Tokens')],
        'TorrentInfo': [('app.domain.context', 'TorrentInfo'), ('app.sdk.media', 'TorrentInfo')],
        'WordsMatcher': [('app.domain.meta.words', 'WordsMatcher'), ('app.sdk.media', 'WordsMatcher')],
        'audio_quality_score': [('app.domain.meta.metamusic', 'audio_quality_score'), ('app.sdk.media', 'audio_quality_score')],
        'audio_quality_tier': [('app.domain.meta.metamusic', 'audio_quality_tier'), ('app.sdk.media', 'audio_quality_tier')],
        'build_media_key': [('app.sdk.media', 'build_media_key')],
        'clear_parsed_title_for_parent_merge': [('app.domain.meta.infopath', 'clear_parsed_title_for_parent_merge'), ('app.sdk.media', 'clear_parsed_title_for_parent_merge')],
        'configure_search_source_provider': [('app.sdk.media', 'configure_search_source_provider')],
        'find_metainfo': [('app.domain.metainfo', 'find_metainfo'), ('app.sdk.media', 'find_metainfo')],
        'format_audio_quality': [('app.domain.meta.metamusic', 'format_audio_quality'), ('app.sdk.media', 'format_audio_quality')],
        'get_custom_release_groups': [('app.domain.meta.releasegroup', 'get_custom_release_groups'), ('app.sdk.media', 'get_custom_release_groups')],
        'get_custom_words': [('app.domain.meta.words', 'get_custom_words'), ('app.sdk.media', 'get_custom_words')],
        'get_customization': [('app.domain.meta.customization', 'get_customization'), ('app.sdk.media', 'get_customization')],
        'infer_audio_lossless': [('app.domain.meta.metamusic', 'infer_audio_lossless'), ('app.sdk.media', 'infer_audio_lossless')],
        'is_anime': [('app.domain.metainfo', 'is_anime'), ('app.sdk.media', 'is_anime')],
        'is_media_source_enabled': [('app.sdk.media', 'is_media_source_enabled')],
        'is_media_source_selected': [('app.sdk.media', 'is_media_source_selected')],
        'is_music_media_source': [('app.sdk.media', 'is_music_media_source')],
        'normalize_audio_format': [('app.domain.meta.metamusic', 'normalize_audio_format'), ('app.sdk.media', 'normalize_audio_format')],
        'normalize_media_identity_payload': [('app.sdk.media', 'normalize_media_identity_payload')],
        'normalize_media_source': [('app.sdk.media', 'normalize_media_source')],
        'normalize_music_type': [('app.sdk.media', 'normalize_music_type')],
        'parse_audio_quality': [('app.domain.meta.metamusic', 'parse_audio_quality'), ('app.sdk.media', 'parse_audio_quality')],
        'parse_media_key': [('app.sdk.media', 'parse_media_key')],
        'parse_media_source_selection': [('app.sdk.media', 'parse_media_source_selection')],
        'resolve_media_identity': [('app.sdk.media', 'resolve_media_identity')],
        'should_use_parent_title_for_file_stem': [('app.domain.meta.infopath', 'should_use_parent_title_for_file_stem'), ('app.sdk.media', 'should_use_parent_title_for_file_stem')],
    },
    'app.sdk.network': {
        'AsyncRequestUtils': [('app.adapters.network.http', 'AsyncRequestUtils')],
        'IpUtils': [('app.adapters.network.ip', 'IpUtils')],
        'RequestUtils': [('app.adapters.network.http', 'RequestUtils')],
        'RssHelper': [('app.application.rss', 'RssHelper')],
        'SiteUtils': [('app.domain.site', 'SiteUtils')],
        'SitesHelper': [('app.application.site.sites', 'SitesHelper')],
        'UrlUtils': [('app.foundation.url', 'UrlUtils')],
        'WebUtils': [('app.adapters.external.location', 'WebUtils')],
        'base_url': [('app.foundation.url', 'base_url')],
        'cookie_parse': [('app.adapters.network.http', 'cookie_parse')],
        'extract_domain': [('app.domain.site', 'extract_domain')],
        'host_label': [('app.foundation.url', 'host_label')],
        'is_link': [('app.foundation.url', 'is_link')],
        'parse_address': [('app.foundation.url', 'parse_address')],
        'sanitize_path': [('app.foundation.url', 'sanitize_path')],
        'second_level_label': [('app.foundation.url', 'second_level_label')],
        'split_netloc': [('app.foundation.url', 'split_netloc')],
        'urls_match': [('app.domain.site', 'urls_match')],
    },
    'app.sdk.plugins': {
        'ModuleManager': [('app.runtime.extensions.module_manager', 'ModuleManager')],
        'PluginManager': [('app.runtime.extensions.plugin_manager', 'PluginManager')],
    },
    'app.sdk.security': {
        'ALGORITHM': [('app.sdk.security', 'ALGORITHM')],
        'BCRYPT_PASSWORD_MAX_BYTES': [('app.sdk.security', 'BCRYPT_PASSWORD_MAX_BYTES')],
        'BCRYPT_ROUNDS': [('app.sdk.security', 'BCRYPT_ROUNDS')],
        'PasswordTooLongError': [('app.sdk.security', 'PasswordTooLongError')],
        'TokenValidationError': [('app.sdk.security', 'TokenValidationError')],
        'aes_decrypt': [('app.sdk.security', 'aes_decrypt')],
        'aes_encrypt': [('app.sdk.security', 'aes_encrypt')],
        'anthropic_api_key_header': [('app.sdk.security', 'anthropic_api_key_header')],
        'api_key_header': [('app.sdk.security', 'api_key_header')],
        'api_key_query': [('app.sdk.security', 'api_key_query')],
        'api_token_query': [('app.sdk.security', 'api_token_query')],
        'create_access_token': [('app.sdk.security', 'create_access_token')],
        'decode_access_token': [('app.sdk.security', 'decode_access_token')],
        'decrypt': [('app.sdk.security', 'decrypt')],
        'encrypt_message': [('app.sdk.security', 'encrypt_message')],
        'get_password_hash': [('app.sdk.security', 'get_password_hash')],
        'hash_sha256': [('app.sdk.security', 'hash_sha256')],
        'nexusphp_encrypt': [('app.sdk.security', 'nexusphp_encrypt')],
        'oauth2_scheme_manual_error': [('app.sdk.security', 'oauth2_scheme_manual_error')],
        'openai_bearer_scheme': [('app.sdk.security', 'openai_bearer_scheme')],
        'resource_token_cookie': [('app.sdk.security', 'resource_token_cookie')],
        'set_or_refresh_resource_token_cookie': [('app.sdk.security', 'set_or_refresh_resource_token_cookie')],
        'set_superuser_token_payload_provider': [('app.sdk.security', 'set_superuser_token_payload_provider')],
        'verify_apikey': [('app.sdk.security', 'verify_apikey')],
        'verify_apitoken': [('app.sdk.security', 'verify_apitoken')],
        'verify_password': [('app.sdk.security', 'verify_password')],
        'verify_resource_token': [('app.sdk.security', 'verify_resource_token')],
        'verify_token': [('app.sdk.security', 'verify_token')],
    },
    'app.sdk.services': {
        'AsyncMediaServerQueryRepository': [('app.application.mediaserver', 'AsyncMediaServerQueryRepository')],
        'DownloaderHelper': [('app.application.downloader', 'DownloaderHelper')],
        'FilterRuleOriginService': [('app.application.rules', 'FilterRuleOriginService')],
        'MediaServerHelper': [('app.application.mediaserver', 'MediaServerHelper')],
        'MediaServerQueryService': [('app.application.mediaserver', 'MediaServerQueryService')],
        'NotificationHelper': [('app.application.notification', 'NotificationHelper')],
        'RuleHelper': [('app.application.rules', 'RuleHelper')],
        'ServiceBaseHelper': [('app.runtime.extensions.service_registry', 'ServiceBaseHelper')],
        'ServiceConfigHelper': [('app.runtime.extensions.service_registry', 'ServiceConfigHelper')],
        'StorageHelper': [('app.application.storage', 'StorageHelper')],
        'SystemHelper': [('app.runtime.state', 'SystemHelper')],
    },
    'app.sdk.utilities': {
        'AbstractSingleton': [('app.foundation.singleton', 'AbstractSingleton'), ('app.sdk.utilities', 'AbstractSingleton')],
        'AbstractSingletonClass': [('app.foundation.singleton', 'AbstractSingletonClass'), ('app.sdk.utilities', 'AbstractSingletonClass')],
        'CryptoJsUtils': [('app.foundation.crypto', 'CryptoJsUtils'), ('app.sdk.utilities', 'CryptoJsUtils')],
        'DomUtils': [('app.foundation.dom', 'DomUtils'), ('app.sdk.utilities', 'DomUtils')],
        'HashUtils': [('app.foundation.crypto', 'HashUtils'), ('app.sdk.utilities', 'HashUtils')],
        'LocaleHelper': [('app.runtime.localization', 'LocaleHelper'), ('app.sdk.utilities', 'LocaleHelper')],
        'ModuleHelper': [('app.foundation.reflection', 'ModuleHelper'), ('app.sdk.utilities', 'ModuleHelper')],
        'ObjectUtils': [('app.foundation.reflection', 'ObjectUtils'), ('app.sdk.utilities', 'ObjectUtils')],
        'OtpUtils': [('app.application.security.otp', 'OtpUtils'), ('app.sdk.utilities', 'OtpUtils')],
        'RSAUtils': [('app.foundation.crypto', 'RSAUtils'), ('app.sdk.utilities', 'RSAUtils')],
        'Singleton': [('app.foundation.singleton', 'Singleton'), ('app.sdk.utilities', 'Singleton')],
        'SingletonClass': [('app.foundation.singleton', 'SingletonClass'), ('app.sdk.utilities', 'SingletonClass')],
        'StringUtils': [('app.sdk.string', 'StringUtils'), ('app.sdk.utilities', 'StringUtils')],
        'SystemUtils': [('app.adapters.system.host', 'SystemUtils'), ('app.sdk.utilities', 'SystemUtils')],
        'TimerUtils': [('app.runtime.scheduling', 'TimerUtils'), ('app.sdk.utilities', 'TimerUtils')],
        'WeakSingleton': [('app.foundation.singleton', 'WeakSingleton'), ('app.sdk.utilities', 'WeakSingleton')],
        'common_prefix': [('app.foundation.text', 'common_prefix'), ('app.sdk.utilities', 'common_prefix')],
        'contains_chinese': [('app.foundation.text', 'contains_chinese'), ('app.sdk.utilities', 'contains_chinese')],
        'contains_japanese': [('app.foundation.text', 'contains_japanese'), ('app.sdk.utilities', 'contains_japanese')],
        'contains_korean': [('app.foundation.text', 'contains_korean'), ('app.sdk.utilities', 'contains_korean')],
        'cookiejar_to_string': [('app.foundation.text', 'cookiejar_to_string'), ('app.sdk.utilities', 'cookiejar_to_string')],
        'count_words': [('app.foundation.text', 'count_words'), ('app.sdk.utilities', 'count_words')],
        'cut': [('app.foundation.text', 'cut'), ('app.sdk.utilities', 'cut')],
        'decrypt': [('app.sdk.utilities', 'decrypt')],
        'encrypt': [('app.sdk.utilities', 'encrypt')],
        'escape_markdown': [('app.foundation.text', 'escape_markdown'), ('app.sdk.utilities', 'escape_markdown')],
        'extract_named_ids': [('app.foundation.text', 'extract_named_ids'), ('app.sdk.utilities', 'extract_named_ids')],
        'format_amount': [('app.foundation.text', 'format_amount'), ('app.sdk.utilities', 'format_amount')],
        'is_all_chinese': [('app.foundation.text', 'is_all_chinese'), ('app.sdk.utilities', 'is_all_chinese')],
        'is_english_word': [('app.foundation.text', 'is_english_word'), ('app.sdk.utilities', 'is_english_word')],
        'is_number': [('app.foundation.text', 'is_number'), ('app.sdk.utilities', 'is_number')],
        'log_execution_time': [('app.sdk.utilities', 'log_execution_time')],
        'natural_sort_key': [('app.foundation.text', 'natural_sort_key'), ('app.sdk.utilities', 'natural_sort_key')],
        'normalize_upper': [('app.foundation.text', 'normalize_upper'), ('app.sdk.utilities', 'normalize_upper')],
        'parse_bool': [('app.foundation.text', 'parse_bool'), ('app.sdk.utilities', 'parse_bool')],
        'parse_float': [('app.foundation.text', 'parse_float'), ('app.sdk.utilities', 'parse_float')],
        'parse_int': [('app.foundation.text', 'parse_int'), ('app.sdk.utilities', 'parse_int')],
        'random_string': [('app.foundation.text', 'random_string'), ('app.sdk.utilities', 'random_string')],
        'remove_punctuation': [('app.foundation.text', 'remove_punctuation'), ('app.sdk.utilities', 'remove_punctuation')],
        'retry': [('app.sdk.utilities', 'retry')],
        'sanitize_filename': [('app.foundation.text', 'sanitize_filename'), ('app.sdk.utilities', 'sanitize_filename')],
        'split_by_bytes': [('app.foundation.text', 'split_by_bytes'), ('app.sdk.utilities', 'split_by_bytes')],
        'strip_optional': [('app.foundation.text', 'strip_optional'), ('app.sdk.utilities', 'strip_optional')],
        'title_case': [('app.foundation.text', 'title_case'), ('app.sdk.utilities', 'title_case')],
    },
}

SDK_DECLARED_EXPORTS = {
    'app.sdk.agent': {
        'MoviePilotTool': ('app.agent.tools.base', 'MoviePilotTool'),
        'StreamingHandler': ('app.agent.tools.base', '_StreamingHandlerProtocol'),
        'ToolTag': ('app.agent.tools.tags', 'ToolTag'),
    },
    'app.sdk.auth': {
        'AuthEntry': ('app.runtime.extensions.projection.auth_entries', 'AuthEntry'),
        'create_plugin_auth_ticket_for_identity': ('app.application.security.auth', 'create_plugin_auth_ticket_for_identity'),
        'list_auth_entries': ('app.runtime.extensions.projection.auth_entries', 'list_auth_entries'),
    },
    'app.sdk.browser': {
        'launch_browser_context': ('app.sdk.browser', 'launch_browser_context'),
        'launch_browser_context_async': ('app.sdk.browser', 'launch_browser_context_async'),
    },
    'app.sdk.cache': {
        'AsyncCache': ('app.runtime.cache', 'AsyncCache'),
        'AsyncCacheBackend': ('app.runtime.cache', 'AsyncCacheBackend'),
        'AsyncFileBackend': ('app.adapters.cache.backends', 'AsyncFileBackend'),
        'AsyncFileCache': ('app.runtime.cache', 'AsyncFileCache'),
        'AsyncMemoryBackend': ('app.runtime.cache', 'AsyncMemoryBackend'),
        'AsyncRedisBackend': ('app.adapters.cache.backends', 'AsyncRedisBackend'),
        'Cache': ('app.runtime.cache', 'Cache'),
        'CacheBackend': ('app.runtime.cache', 'CacheBackend'),
        'FileBackend': ('app.adapters.cache.backends', 'FileBackend'),
        'FileCache': ('app.runtime.cache', 'FileCache'),
        'LRUCache': ('app.runtime.cache', 'LRUCache'),
        'MemoryBackend': ('app.runtime.cache', 'MemoryBackend'),
        'RedisBackend': ('app.adapters.cache.backends', 'RedisBackend'),
        'TTLCache': ('app.runtime.cache', 'TTLCache'),
        'async_fresh': ('app.runtime.cache', 'async_fresh'),
        'cached': ('app.runtime.cache', 'cached'),
        'fresh': ('app.runtime.cache', 'fresh'),
        'is_fresh': ('app.runtime.cache', 'is_fresh'),
    },
    'app.sdk.config': {
        'ConfigModel': ('app.runtime.config', 'ConfigModel'),
        'GlobalVar': ('app.runtime.config', 'GlobalVar'),
        'Settings': ('app.runtime.config', 'Settings'),
        'SystemConfModel': ('app.runtime.config', 'SystemConfModel'),
        'global_vars': ('app.runtime.config', 'global_vars'),
        'settings': ('app.runtime.config', 'settings'),
    },
    'app.sdk.database': {
        'BackupArtifact': ('app.application.backup', 'BackupArtifact'),
        'BackupVerification': ('app.application.backup', 'BackupVerification'),
        'PluginDatabaseHandle': ('app.db.plugin', 'PluginDatabaseHandle'),
        'create_backup': ('app.sdk.database', 'create_backup'),
        'list_backups': ('app.sdk.database', 'list_backups'),
        'verify_backup': ('app.sdk.database', 'verify_backup'),
    },
    'app.sdk.declarations': {
        'ActionDeclaration': ('app.runtime.extensions.contract.declaration', 'ActionDeclaration'),
        'AgentToolDeclaration': ('app.runtime.extensions.contract.declaration', 'AgentToolDeclaration'),
        'CommandDeclaration': ('app.runtime.extensions.contract.declaration', 'CommandDeclaration'),
        'DashboardDeclaration': ('app.runtime.extensions.contract.declaration', 'DashboardDeclaration'),
        'ExtensionDeclaration': ('app.runtime.extensions.contract.declaration', 'ExtensionDeclaration'),
        'FilterRuleDeclaration': ('app.runtime.extensions.contract.declaration', 'FilterRuleDeclaration'),
        'FilterRuleGroupDeclaration': ('app.runtime.extensions.contract.declaration', 'FilterRuleGroupDeclaration'),
        'MediaSourceDeclaration': ('app.runtime.extensions.contract.declaration', 'MediaSourceDeclaration'),
        'MetaParserDeclaration': ('app.runtime.extensions.contract.declaration', 'MetaParserDeclaration'),
        'ModuleDeclaration': ('app.runtime.extensions.contract.declaration', 'ModuleDeclaration'),
        'ScheduleDeclaration': ('app.runtime.extensions.contract.declaration', 'ScheduleDeclaration'),
        'ServiceInstanceDeclaration': ('app.runtime.extensions.contract.declaration', 'ServiceInstanceDeclaration'),
        'ServiceInstanceRequirement': ('app.runtime.extensions.contract.declaration', 'ServiceInstanceRequirement'),
    },
    'app.sdk.events': {
        'Event': ('app.runtime.events', 'Event'),
        'EventHandlerBinding': ('app.runtime.events', 'EventHandlerBinding'),
        'EventManager': ('app.runtime.events', 'EventManager'),
        'eventmanager': ('app.runtime.events', 'eventmanager'),
    },
    'app.sdk.extension': {
        'ChainDataPorts': ('app.application.orchestration.data', 'ChainDataPorts'),
        'ChainDurableEventWriter': ('app.application.orchestration.durable_events', 'ChainDurableEventWriter'),
        'ChainRuntimeConfig': ('app.application.configuration', 'ChainRuntimeConfig'),
        'ChainRuntimeContext': ('app.application.orchestration.context', 'ChainRuntimeContext'),
        'PluginChian': ('app.sdk.extension', 'PluginChian'),
        'TransferHistoryRecord': ('app.application.history', 'TransferHistoryRecord'),
        'TransferHistoryWriter': ('app.application.history', 'TransferHistoryWriter'),
        '_PluginBase': ('app.sdk.extension', '_PluginBase'),
    },
    'app.sdk.logging': {
        'LogWriter': ('app.runtime.log', 'LogWriter'),
        'logger': ('app.runtime.log', 'logger'),
    },
    'app.sdk.media': {
        'Context': ('app.domain.context', 'Context'),
        'CustomizationMatcher': ('app.domain.meta.customization', 'CustomizationMatcher'),
        'MEDIA_SOURCE_ALIASES': ('app.schemas.media', 'MEDIA_SOURCE_ALIASES'),
        'MEDIA_SOURCE_PREFIXES': ('app.schemas.media', 'MEDIA_SOURCE_PREFIXES'),
        'MUSIC_MEDIA_SOURCES': ('app.domain.media', 'MUSIC_MEDIA_SOURCES'),
        'MUSIC_MEDIA_SOURCE_ORDER': ('app.domain.media', 'MUSIC_MEDIA_SOURCE_ORDER'),
        'MediaInfo': ('app.domain.context', 'MediaInfo'),
        'MetaAnime': ('app.domain.meta.metaanime', 'MetaAnime'),
        'MetaBase': ('app.domain.meta.metabase', 'MetaBase'),
        'MetaFieldRevision': ('app.schemas.metaparse', 'MetaFieldRevision'),
        'MetaInfo': ('app.domain.metainfo', 'MetaInfo'),
        'MetaInfoPath': ('app.domain.metainfo', 'MetaInfoPath'),
        'MetaMusic': ('app.domain.meta.metamusic', 'MetaMusic'),
        'MetaParseStatus': ('app.schemas.metaparse', 'MetaParseStatus'),
        'MetaParseTrace': ('app.schemas.metaparse', 'MetaParseTrace'),
        'MetaParserRun': ('app.schemas.metaparse', 'MetaParserRun'),
        'MetaVideo': ('app.domain.meta.metavideo', 'MetaVideo'),
        'MusicAlbumInfo': ('app.domain.context', 'MusicAlbumInfo'),
        'MusicArtistInfo': ('app.domain.context', 'MusicArtistInfo'),
        'MusicInfo': ('app.domain.context', 'MusicInfo'),
        'MusicLyrics': ('app.domain.context', 'MusicLyrics'),
        'MusicNameContext': ('app.domain.meta.metamusic', 'MusicNameContext'),
        'MusicNameParseResult': ('app.domain.meta.metamusic', 'MusicNameParseResult'),
        'MusicNameParser': ('app.domain.meta.metamusic', 'MusicNameParser'),
        'MusicNamePattern': ('app.domain.meta.metamusic', 'MusicNamePattern'),
        'MusicNamePatternMatch': ('app.domain.meta.metamusic', 'MusicNamePatternMatch'),
        'MusicNameRegistry': ('app.domain.meta.metamusic', 'MusicNameRegistry'),
        'MusicRelease': ('app.domain.context', 'MusicRelease'),
        'NfoReader': ('app.domain.scraper', 'NfoReader'),
        'ReleaseGroupsMatcher': ('app.domain.meta.releasegroup', 'ReleaseGroupsMatcher'),
        'StreamingPlatforms': ('app.domain.meta.streamingplatform', 'StreamingPlatforms'),
        'SubtitleInfo': ('app.domain.context', 'SubtitleInfo'),
        'Tokens': ('app.domain.tokens', 'Tokens'),
        'TorrentInfo': ('app.domain.context', 'TorrentInfo'),
        'WordsMatcher': ('app.domain.meta.words', 'WordsMatcher'),
        'audio_quality_score': ('app.domain.meta.metamusic', 'audio_quality_score'),
        'audio_quality_tier': ('app.domain.meta.metamusic', 'audio_quality_tier'),
        'build_media_key': ('app.schemas.media', 'build_media_key'),
        'clear_parsed_title_for_parent_merge': ('app.domain.meta.infopath', 'clear_parsed_title_for_parent_merge'),
        'configure_search_source_provider': ('app.domain.media', 'configure_search_source_provider'),
        'find_metainfo': ('app.domain.metainfo', 'find_metainfo'),
        'format_audio_quality': ('app.domain.meta.metamusic', 'format_audio_quality'),
        'get_custom_release_groups': ('app.domain.meta.releasegroup', 'get_custom_release_groups'),
        'get_custom_words': ('app.domain.meta.words', 'get_custom_words'),
        'get_customization': ('app.domain.meta.customization', 'get_customization'),
        'infer_audio_lossless': ('app.domain.meta.metamusic', 'infer_audio_lossless'),
        'is_anime': ('app.domain.metainfo', 'is_anime'),
        'is_media_source_enabled': ('app.domain.media', 'is_media_source_enabled'),
        'is_media_source_selected': ('app.domain.media', 'is_media_source_selected'),
        'is_music_media_source': ('app.domain.media', 'is_music_media_source'),
        'normalize_audio_format': ('app.domain.meta.metamusic', 'normalize_audio_format'),
        'normalize_media_identity_payload': ('app.schemas.media', 'normalize_media_identity_payload'),
        'normalize_media_source': ('app.schemas.media', 'normalize_media_source'),
        'normalize_music_type': ('app.domain.media', 'normalize_music_type'),
        'parse_audio_quality': ('app.domain.meta.metamusic', 'parse_audio_quality'),
        'parse_media_key': ('app.schemas.media', 'parse_media_key'),
        'parse_media_source_selection': ('app.domain.media', 'parse_media_source_selection'),
        'resolve_media_identity': ('app.schemas.media', 'resolve_media_identity'),
        'should_use_parent_title_for_file_stem': ('app.domain.meta.infopath', 'should_use_parent_title_for_file_stem'),
    },
    'app.sdk.network': {
        'AsyncRequestUtils': ('app.adapters.network.http', 'AsyncRequestUtils'),
        'IpUtils': ('app.adapters.network.ip', 'IpUtils'),
        'RequestUtils': ('app.adapters.network.http', 'RequestUtils'),
        'RssHelper': ('app.application.rss', 'RssHelper'),
        'SecurityUtils': ('app.adapters.network.urlsafety', 'SecurityUtils'),
        'SiteUtils': ('app.domain.site', 'SiteUtils'),
        'SitesHelper': ('app.application.site.sites', 'SitesHelper'),
        'UrlSafetyDiagnosis': ('app.adapters.network.urlsafety', 'UrlSafetyDiagnosis'),
        'UrlSafetyReason': ('app.adapters.network.urlsafety', 'UrlSafetyReason'),
        'UrlUtils': ('app.foundation.url', 'UrlUtils'),
        'WebUtils': ('app.adapters.external.location', 'WebUtils'),
        'base_url': ('app.foundation.url', 'base_url'),
        'cookie_parse': ('app.adapters.network.http', 'cookie_parse'),
        'extract_domain': ('app.domain.site', 'extract_domain'),
        'host_label': ('app.foundation.url', 'host_label'),
        'is_link': ('app.foundation.url', 'is_link'),
        'parse_address': ('app.foundation.url', 'parse_address'),
        'sanitize_path': ('app.foundation.url', 'sanitize_path'),
        'second_level_label': ('app.foundation.url', 'second_level_label'),
        'split_netloc': ('app.foundation.url', 'split_netloc'),
        'urls_match': ('app.domain.site', 'urls_match'),
    },
    'app.sdk.plugins': {
        'ActivationPolicy': ('app.runtime.capabilities.model', 'ActivationPolicy'),
        'CapabilitySpec': ('app.runtime.capabilities.model', 'CapabilitySpec'),
        'ModuleManager': ('app.runtime.extensions.module_manager', 'ModuleManager'),
        'PluginDependencyClassification': ('app.runtime.extensions.contract.dependency', 'PluginDependencyClassification'),
        'PluginDependencyInstallResult': ('app.runtime.extensions.contract.dependency', 'PluginDependencyInstallResult'),
        'PluginManager': ('app.runtime.extensions.plugin_manager', 'PluginManager'),
        'SelectorSpec': ('app.runtime.capabilities.model', 'SelectorSpec'),
    },
    'app.sdk.security': {
        'ALGORITHM': ('app.application.security.token', 'ALGORITHM'),
        'BCRYPT_PASSWORD_MAX_BYTES': ('app.application.security.token', 'BCRYPT_PASSWORD_MAX_BYTES'),
        'BCRYPT_ROUNDS': ('app.application.security.token', 'BCRYPT_ROUNDS'),
        'PasswordTooLongError': ('app.application.security.token', 'PasswordTooLongError'),
        'TokenValidationError': ('app.application.security.token', 'TokenValidationError'),
        'aes_decrypt': ('app.application.security.token', 'aes_decrypt'),
        'aes_encrypt': ('app.application.security.token', 'aes_encrypt'),
        'anthropic_api_key_header': ('app.adapters.web.security.access', 'anthropic_api_key_header'),
        'api_key_header': ('app.adapters.web.security.access', 'api_key_header'),
        'api_key_query': ('app.adapters.web.security.access', 'api_key_query'),
        'api_token_query': ('app.adapters.web.security.access', 'api_token_query'),
        'create_access_token': ('app.application.security.token', 'create_access_token'),
        'decode_access_token': ('app.application.security.token', 'decode_access_token'),
        'decrypt': ('app.application.security.token', 'decrypt'),
        'encrypt_message': ('app.application.security.token', 'encrypt_message'),
        'get_password_hash': ('app.application.security.token', 'get_password_hash'),
        'hash_sha256': ('app.application.security.token', 'hash_sha256'),
        'nexusphp_encrypt': ('app.application.security.token', 'nexusphp_encrypt'),
        'oauth2_scheme_manual_error': ('app.adapters.web.security.access', 'oauth2_scheme_manual_error'),
        'openai_bearer_scheme': ('app.adapters.web.security.access', 'openai_bearer_scheme'),
        'resource_token_cookie': ('app.adapters.web.security.access', 'resource_token_cookie'),
        'set_or_refresh_resource_token_cookie': ('app.adapters.web.security.access', 'set_or_refresh_resource_token_cookie'),
        'set_superuser_token_payload_provider': ('app.adapters.web.security.access', 'set_superuser_token_payload_provider'),
        'verify_apikey': ('app.adapters.web.security.access', 'verify_apikey'),
        'verify_apitoken': ('app.adapters.web.security.access', 'verify_apitoken'),
        'verify_password': ('app.application.security.token', 'verify_password'),
        'verify_resource_token': ('app.adapters.web.security.access', 'verify_resource_token'),
        'verify_token': ('app.adapters.web.security.access', 'verify_token'),
    },
    'app.sdk.service_instances': {
        'DownloaderInstance': ('app.sdk.service_instances', 'DownloaderInstance'),
        'MediaServerInstance': ('app.sdk.service_instances', 'MediaServerInstance'),
        'NotificationInstance': ('app.sdk.service_instances', 'NotificationInstance'),
        'service_capabilities': ('app.sdk.service_instances', 'service_capabilities'),
        'service_instance_required_methods': ('app.sdk.service_instances', 'service_instance_required_methods'),
    },
    'app.sdk.services': {
        'AsyncMediaServerQueryRepository': ('app.application.mediaserver', 'AsyncMediaServerQueryRepository'),
        'DownloaderHelper': ('app.application.downloader', 'DownloaderHelper'),
        'FilterRuleOriginService': ('app.application.rules', 'FilterRuleOriginService'),
        'MediaServerHelper': ('app.application.mediaserver', 'MediaServerHelper'),
        'MediaServerIdentityHelper': ('app.domain.library', 'MediaServerIdentityHelper'),
        'MediaServerQueryService': ('app.application.mediaserver', 'MediaServerQueryService'),
        'MusicMediaServerHelper': ('app.domain.library', 'MusicMediaServerHelper'),
        'NotificationHelper': ('app.application.notification', 'NotificationHelper'),
        'RuleHelper': ('app.application.rules', 'RuleHelper'),
        'ServiceBaseHelper': ('app.runtime.extensions.service_registry', 'ServiceBaseHelper'),
        'ServiceConfigHelper': ('app.runtime.extensions.service_config', 'ServiceConfigHelper'),
        'StorageHelper': ('app.application.storage', 'StorageHelper'),
        'SystemHelper': ('app.runtime.state', 'SystemHelper'),
        'declared_service_instances': ('app.runtime.extensions.registry.service_instance', 'declared_service_instances'),
    },
    'app.sdk.storage': {
        'StorageBase': ('app.modules._base.storage', 'StorageBase'),
        'StorageInstanceSingleton': ('app.modules._base.storage', 'StorageInstanceSingleton'),
        'transfer_process': ('app.modules._base.storage', 'transfer_process'),
    },
    'app.sdk.string': {
        'StringUtils': ('app.sdk.string', 'StringUtils'),
    },
    'app.sdk.types': {
        'ChainEventType': ('app.schemas.types', 'ChainEventType'),
        'EventType': ('app.schemas.types', 'EventType'),
        'MediaImageType': ('app.schemas.types', 'MediaImageType'),
        'SystemConfigKey': ('app.schemas.types', 'SystemConfigKey'),
        'TorrentStatus': ('app.schemas.types', 'TorrentStatus'),
    },
    'app.sdk.utilities': {
        'AbstractSingleton': ('app.foundation.singleton', 'AbstractSingleton'),
        'AbstractSingletonClass': ('app.foundation.singleton', 'AbstractSingletonClass'),
        'CryptoJsUtils': ('app.foundation.crypto', 'CryptoJsUtils'),
        'DomUtils': ('app.foundation.dom', 'DomUtils'),
        'HashUtils': ('app.foundation.crypto', 'HashUtils'),
        'LocaleHelper': ('app.runtime.localization', 'LocaleHelper'),
        'ModuleHelper': ('app.foundation.reflection', 'ModuleHelper'),
        'ObjectUtils': ('app.foundation.reflection', 'ObjectUtils'),
        'OtpUtils': ('app.application.security.otp', 'OtpUtils'),
        'RSAUtils': ('app.foundation.crypto', 'RSAUtils'),
        'Singleton': ('app.foundation.singleton', 'Singleton'),
        'SingletonClass': ('app.foundation.singleton', 'SingletonClass'),
        'StringUtils': ('app.sdk.string', 'StringUtils'),
        'SystemUtils': ('app.adapters.system.host', 'SystemUtils'),
        'TimerUtils': ('app.runtime.scheduling', 'TimerUtils'),
        'WeakSingleton': ('app.foundation.singleton', 'WeakSingleton'),
        'common_prefix': ('app.foundation.text', 'common_prefix'),
        'contains_chinese': ('app.foundation.text', 'contains_chinese'),
        'contains_japanese': ('app.foundation.text', 'contains_japanese'),
        'contains_korean': ('app.foundation.text', 'contains_korean'),
        'cookiejar_to_string': ('app.foundation.text', 'cookiejar_to_string'),
        'count_words': ('app.foundation.text', 'count_words'),
        'cut': ('app.foundation.text', 'cut'),
        'decrypt': ('app.sdk.utilities', 'decrypt'),
        'encrypt': ('app.sdk.utilities', 'encrypt'),
        'escape_markdown': ('app.foundation.text', 'escape_markdown'),
        'extract_named_ids': ('app.foundation.text', 'extract_named_ids'),
        'format_amount': ('app.foundation.text', 'format_amount'),
        'is_all_chinese': ('app.foundation.text', 'is_all_chinese'),
        'is_english_word': ('app.foundation.text', 'is_english_word'),
        'is_number': ('app.foundation.text', 'is_number'),
        'log_execution_time': ('app.runtime.execution', 'log_execution_time'),
        'natural_sort_key': ('app.foundation.text', 'natural_sort_key'),
        'normalize_upper': ('app.foundation.text', 'normalize_upper'),
        'parse_bool': ('app.foundation.text', 'parse_bool'),
        'parse_float': ('app.foundation.text', 'parse_float'),
        'parse_int': ('app.foundation.text', 'parse_int'),
        'random_string': ('app.foundation.text', 'random_string'),
        'remove_punctuation': ('app.foundation.text', 'remove_punctuation'),
        'retry': ('app.runtime.execution', 'retry'),
        'sanitize_filename': ('app.foundation.text', 'sanitize_filename'),
        'split_by_bytes': ('app.foundation.text', 'split_by_bytes'),
        'strip_optional': ('app.foundation.text', 'strip_optional'),
        'title_case': ('app.foundation.text', 'title_case'),
    },
}

SDK_HOST_INTERNAL_EXPORTS = {
    'app.adapters.network.http.aclose_shared_async_transports': '关闭宿主共享异步连接池，属应用关停流程',
    'app.adapters.network.http.configure_default_user_agent': '设置宿主全局默认 User-Agent',
    'app.adapters.network.http.get_caller': '回溯宿主调用栈以标注请求来源',
    'app.domain.context.configure_tmdb_image_url_builder': '装配宿主 TMDB 图片地址构造器',
    'app.domain.meta.customization.configure_customization_provider': '装配宿主自定义识别词提供者',
    'app.domain.meta.releasegroup.configure_release_groups_provider': '装配宿主自定义制作组提供者',
    'app.domain.meta.words.configure_custom_words_provider': '装配宿主自定义占位词提供者',
    'app.domain.metainfo.clear_rust_parse_options_cache': '重置宿主解析加速器的选项缓存',
    'app.domain.scraper.MediaScraperHelper': '刮削助手的取用位置由 app.helper.scraper 条目指向 app.domain.scraper',
    'app.foundation.text.convert': '简繁转换的取用位置由 app.utils.zhconv 条目指向 app.foundation.text',
    'app.runtime.extensions.plugin_manager.configure_plugin_catalog_factory': '装配宿主插件目录工厂',
    'app.runtime.extensions.plugin_manager.configure_plugin_install_reporter': '装配宿主插件安装上报器',
    'app.runtime.extensions.plugin_manager.configure_plugin_legacy_import_services': '装配宿主旧导入诊断服务',
    'app.runtime.extensions.plugin_manager.configure_plugin_resource_import_preparer': '装配宿主插件资源导入准备器',
    'app.runtime.extensions.plugin_manager.configure_site_auth_level_provider': '装配宿主站点认证级别提供者',
}

SDK_PLUGIN_BASE_SURFACE = {
    'attributes': [
        'chain',
        'eventmanager',
        'instance_id',
        'plugin_id',
        'plugindata',
        'systemconfig',
        'systemmessage',
    ],
    'members': [
        'async_get_data',
        'async_save_data',
        'close',
        'declare_plugin_migrations',
        'declare_plugin_models',
        'del_data',
        'get_actions',
        'get_agent_tools',
        'get_api',
        'get_auth_providers',
        'get_channel_capabilities',
        'get_command',
        'get_config',
        'get_dashboard',
        'get_dashboard_meta',
        'get_data',
        'get_data_path',
        'get_form',
        'get_instance_key',
        'get_media_source',
        'get_module',
        'get_name',
        'get_page',
        'get_plugin_database',
        'get_render_mode',
        'get_service',
        'get_state',
        'init_plugin',
        'instance_id',
        'plugin_desc',
        'plugin_id',
        'plugin_name',
        'plugin_order',
        'post_message',
        'provides_actions',
        'provides_agent_tools',
        'provides_channel_capabilities',
        'provides_commands',
        'provides_dashboards',
        'provides_filter_rule_groups',
        'provides_filter_rules',
        'provides_media_sources',
        'provides_meta_parsers',
        'provides_modules',
        'provides_schedules',
        'provides_service_instances',
        'save_data',
        'stop_service',
        'test',
        'update_config',
    ],
}
