"""2.0.2

Revision ID: 0fb94bf69b38
Revises: 262735d025da
Create Date: 2024-09-30 10:03:58.546036

"""
import contextlib

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb94bf69b38'
down_revision = '262735d025da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with contextlib.suppress(Exception):
        with op.batch_alter_table("siteuserdata") as batch_op:
            batch_op.add_column(sa.Column('name', sa.VARCHAR))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
