"""1.0.13

Revision ID: 127a25fdf0e8
Revises: d71e624f0208
Create Date: 2024-02-24 03:11:32.005540

"""

import contextlib
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127a25fdf0e8'
down_revision = 'd71e624f0208'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with contextlib.suppress(Exception):
        with op.batch_alter_table("subscribe") as batch_op:
            batch_op.add_column(sa.Column('search_imdbid', sa.Integer, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
