"""1.0.18

Revision ID: 2baf901c87c0
Revises: 9cb3993e340e
Create Date: 2024-04-17 11:58:46.061830

"""
import logging

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2baf901c87c0'
down_revision = '9cb3993e340e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('sysconfig',
                        sa.Column('id', sa.INTEGER(), nullable=False),
                        sa.Column('uid', sa.INTEGER(), nullable=True),
                        sa.Column('mediaStatistic', sa.BOOLEAN(), nullable=True),
                        sa.Column('scheduler', sa.BOOLEAN(), nullable=True),
                        sa.Column('speed', sa.BOOLEAN(), nullable=True),
                        sa.Column('storage', sa.BOOLEAN(), nullable=True),
                        sa.Column('weeklyOverview', sa.BOOLEAN(), nullable=True),
                        sa.Column('cpu', sa.BOOLEAN(), nullable=True),
                        sa.Column('memory', sa.BOOLEAN(), nullable=True),
                        sa.Column('library', sa.BOOLEAN(), nullable=True),
                        sa.Column('playing', sa.BOOLEAN(), nullable=True),
                        sa.Column('latest', sa.BOOLEAN(), nullable=True),
                        sa.PrimaryKeyConstraint('id')
                        )
        op.create_index('ix_sysconfig_uid', 'sysconfig', ['uid'], unique=False)
        op.create_index('ix_sysconfig_id', 'sysconfig', ['id'], unique=False)
    except Exception as e:
        logging.error("An error occurred during database migration: %s", e)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
