"""1.0.7

Revision ID: 30329639c12b
Revises: 232dfa044617
Create Date: 2023-09-23 08:25:59.776488

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '30329639c12b'
down_revision = '232dfa044617'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("delete from systemconfig where key = 'DefaultFilterRules';")
    op.execute(
        "insert into systemconfig(key, value) VALUES('DefaultFilterRules', (select value from systemconfig where key= 'DefaultIncludeExcludeFilter'));")
    op.execute("delete from systemconfig where key = 'DefaultIncludeExcludeFilter';")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
