"""1.0.15

Revision ID: 5813aaa7cb3a
Revises: f94cd1217fd7
Create Date: 2024-03-17 09:04:51.785716

"""
import contextlib

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5813aaa7cb3a'
down_revision = 'f94cd1217fd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with contextlib.suppress(Exception):
        with op.batch_alter_table("message") as batch_op:
            batch_op.add_column(sa.Column('note', sa.String, nullable=True))
    try:
        op.create_index('ix_message_reg_time', 'message', ['reg_time'], unique=False)
    except Exception as err:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
