"""1.0.18

Revision ID: 735c01e0453d
Revises: 9cb3993e340e
Create Date: 2024-04-29 19:40:38.375072

"""
import contextlib

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735c01e0453d'
down_revision = '9cb3993e340e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with contextlib.suppress(Exception):
        with op.batch_alter_table("site") as batch_op:
            batch_op.add_column(sa.Column('apikey', sa.VARCHAR))
            batch_op.add_column(sa.Column('token', sa.VARCHAR))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
