"""1.0.19

Revision ID: ae9d8ed8df97
Revises: 735c01e0453d
Create Date: 2024-05-16 14:21:46.108359

"""
import contextlib

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9d8ed8df97'
down_revision = '735c01e0453d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with contextlib.suppress(Exception):
        with op.batch_alter_table("site") as batch_op:
            batch_op.add_column(sa.Column('timeout', sa.INTEGER))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
