"""1.0.11

Revision ID: dbc87e111355
Revises: d633ca6cd572
Create Date: 2023-10-26 20:47:08.261509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc87e111355'
down_revision = 'd633ca6cd572'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table("downloadhistory") as batch_op:
            batch_op.alter_column('userid', new_column_name='username')
    except Exception as e:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    pass