"""1.0.5

Revision ID: e734c7fe6056
Revises: 1e169250e949
Create Date: 2023-09-07 18:19:41.250957

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e734c7fe6056'
down_revision = '1e169250e949'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_index('ix_transferhistory_tmdbid', 'transferhistory', ['tmdbid'], unique=False)
    except Exception as err:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
