from .objs.account import Account
from .objs.auth import Authentication
from .objs.certification import Certification
from .objs.change import Change
from .objs.collection import Collection
from .objs.company import Company
from .objs.configuration import Configuration
from .objs.credit import Credit
from .objs.discover import Discover
from .objs.episode import Episode
from .objs.find import Find
from .objs.genre import Genre
from .objs.group import Group
from .objs.keyword import Keyword
from .objs.list import List
from .objs.movie import Movie
from .objs.network import Network
from .objs.person import Person
from .objs.provider import Provider
from .objs.review import Review
from .objs.search import Search
from .objs.season import Season
from .objs.trending import Trending
from .objs.tv import TV
from .tmdb import TMDb
